### ISSUE TITLE
Version control in the context of DevOps

### ISSUE THREAD

**Issue by monperrus** [KTH/devops-course#1]
Why it is relevant: most continuous-* technology relies on version control, with Git dominating the area.

**Comment by SimoneStefani** [comment]
I think is important to stress the importance of Git as **a team collaboration and process management tool**. Most students at the moment think of it as a *program to save code*. Focus on workflows (my suggestion is Gitflow).

In the past 2 years I run seminars in KTH Kista about Git (basic Git + Git for teams). Here are the annotated slides:
- [Working Alone with Git](https://drive.google.com/drive/u/0/folders/0B5pC4rbrOn-hbE5ENEw2ZWJ5T3c)
- [Working in Team with Git](https://drive.google.com/drive/u/0/folders/0B5pC4rbrOn-hbE5ENEw2ZWJ5T3c)

More resources on Gitflow:
- [Original article by Vincent Driessen](https://nvie.com/posts/a-successful-git-branching-model/)
- [Gitflow in details by Marcel Eschmann](https://github.com/eschmar/gitflow)

**Comment by monperrus** [comment]
Completely agree @SimoneStefani. Would you be interested in participating/contributing to the course?

**Comment by SimoneStefani** [comment]
@monperrus  Yes, as I briefly discussed with Benoit, I would be glad to contribute and also participate (guest lectures ?) provided that my working schedule will allow.

**Comment by monperrus** [comment]
Excellent, to be discussed in person.

**Comment by monperrus** [comment]
See also IDE in the cloud "Cloud Workspace", https://github.com/codenvy/codenvy

**Comment by monperrus** [comment]
And https://github.com/theia-ide/theia

**Comment by bbaudry** [comment]
[Perforce](https://en.wikipedia.org/wiki/Perforce)

(used at EA/DICE in Stockholm)

**Comment by monperrus** [comment]
Branch by abstraction: https://martinfowler.com/bliki/BranchByAbstraction.html

**Comment by bbaudry** [comment]
From Git Flow to Trunk Based Development
https://team-coder.com/from-git-flow-to-trunk-based-development/

**Comment by monperrus** [comment]
Perforce plugin for Jenkins 
https://github.com/jenkinsci/p4-plugin
