### ISSUE TITLE
breif tool suggestions by a student

### ISSUE THREAD

**Issue by henriklb** [KTH/devops-course#10]
Would love to learn to work with ansible, puppet, chef, git, icinga.

I will have to admit that programming in Java is not very tempting.

**Comment by monperrus** [comment]
Thanks a lot for the suggestions

> ansible, puppet, chef

See #2 

> git

See #1 

> icinga

See #8

**Comment by monperrus** [comment]
> I will have to admit that programming in Java is not very tempting.

Is Java mentioned somewhere?

**Comment by henriklb** [comment]
> Is Java mentioned somewhere?

Sorry, not directly but I assumed since Jenkins was mentioned here: https://www.kth.se/student/kurser/kurs/DD2482?l=en

**Comment by monperrus** [comment]
OK, thanks.
