### ISSUE TITLE
Results 2021

### ISSUE THREAD

**Issue by bbaudry** [KTH/devops-course#1083]
Here we post comments and results.

**Comment by bbaudry** [comment]
## Presentations of Week 2

### DISTINCTION: Third Party Software Dependency Management. Anna Nikolskaya, Carl Leijonberg 👍👍

yes: timing, originality, reflection, loudly, engagement, humour, readable, illustration
remarkable: motivation, technical, take-home

### PASS: Monitoring with Prometheus. Aron Hansen Berggren, Fredrik Björkman 👍

yes: originality, reflection, take-home, loudly, engagement, humour, readable, illustration
remarkable: technical, motivation

### DISTINCTION: The history of DevOps. Hugo Heyman, Patricia Naccachian 👍👍
illustration
yes: timing, motivation, technical, take-home, loudly, engagement, readable, illustration
remarkable: originality, humour, reflection
comments: the scope was ambitious and you succeeded
 
### PASS: DevOps practices in a Sundsvall company. Isac Arvidsson, Andreas Henriksson 👍

yes: timing, technical, humour, reflection, take-home, loudly, engagement, readable, illustration
remarkable:  originality, motivation
 
### DISTINCTION: Reproducible Builds with Nix. Yannik Sander 👍👍

yes: timing, motivation, reflection, loudly, engagement, humour, readable
remarkable: technical, originality, illustration

**Comment by monperrus** [comment]
## Presentations of Week 3

### DISTINCTION ML_OPS: Current applications and future possibilities. Johan Hammarstedt @jhammarstedt , Matej Sestak @sestys  👍👍

yes: technical, illustration, loudly, timing, loudly, engagement (menti competition)

remarkable: reflection, originality, motivation, take-home

comments: agenda is clear, clear definitions, very clear vision and motivation (ML is not Jupyter); mlops verssus devops: clear, good reflection


### REPEAT Overview of Continuous Testing. Gabriel Chang @ChangGabriel, William Skagerström @wska 

yes: engagement, motivation, loudly, readable, timing

Comments: interesting link between testing / business risk, smooth articulation between speakers

For repeat:
- originality: choose one specific novel, timely feature of continuous testing and have a one slide focus on this key point (suggestion: link between continuous testing and user experience, this is original)
- reflection: sharpen the distinction between continuous and automated testing, based on concrete technical and methodological aspects. One possibility: select a case study to illustrate your purpose
- technical criterion: how do you concretely 'embed' business values or business risks into the automation cycle. give a code example.
- take-home: what is the key incentive to consider continuous testing? How can one 'boost' automatic testing? 


### REPEAT Continuous Testing in DevOps. Renugaa, Megha Gangwal @Renugaa @gangwalmegha 

yes: timing, relevance, loudly

Important: add your full name and KTH ids in your README

For repeat
- originality: focus on one point, e.g. the 4 challenges of enterprise testing (slide)
- reflection: express your opinion about opportunities, risks or challenges
- readable/illustration: avoid slides with too many words / too many bullets (e.g. slide 'suggest approach...'), increase font size, have more focused and larger diagrams
- motivation: what is the specific problem that you address in your presentation? 
- technical: can you say more about the challenges from a technical perspective? in the challenges you emphasize 'long times' for many tasks. What are the actions that take time?
- take-home: what is the key technical and novel point you would like the audience to remember from your talk?

minor comments:
- typos in slides:
- add slide numbers, proof-read all the slides
- rehearse the presentation to avoid skipping a slide, and work on the articulation among speakers


###  PASS Cloud and the journey for a start-up to Fortune 500. Adeeb Syed Shah, Rezaul Hasan, Carina Wickström @Internet-Person-IP 

(edit of May 20: the extension on Week 4 validates this one)
Good presentation with an original narrative and a good energy. Fails to meet the rules of the course.


### REPEAT An Introduction to BizDevOps. Lazar Cerovic @lazarko 

yes: illustration, readable, timing, originality

For repeat:
- reflection: crystalize what you believe are the most salient technical features that characterize this specific flavor of DevOps
- loudly / engagement: improve the smoothness of the talk, with more energy and engagement towards the audience
- motivation: what is the concrete problem that you are addressing in this presentation?
- technical: focus on one of the tools that you mention in the slide before last and elaborate on it (e.g., pega agilepoint, wavemaker), incl. a deep dive into one of them
- take-home: what shall your audience, who is very passionate about technology, take from your presentation? 

Comments: 
- elaborate on why your local kebap place is a "software company". 
- bizdevops add a reference to an authoritative source
- add slide numbers

**Comment by bbaudry** [comment]
# Presentations of week 4

### PASS Autoscaling and load balancing. Carina Wickstrom @carinawic, Md Rezaul Hasan @MDRezaulHasan.  👍

yes: timing, originality, loudly, readable, humour (sponge bob), take-home (convincing black friday example)

remarkable: engagement (lots of energy), technical

### PASS Assuring Code Quality with SonarQube. Félix Fonteneau @FelixFonteneau, Hilaire Bouaddi @Hilaire-Bouaddi 👍

yes: timing, motivation,  originality, readable, reflection (relation between quality and scalability, inclusive perspective about code quality), take-home

remarkable: illustration

Comments: 
- it'd be good to deepen the technical aspect of Sonar (the cost of fixing, the false alarms, the number of rules, etc.)
- problem in structure: continuous code inspection is defined twice on two separate slides 

### DISTINCTION GitOps Carl Piehl @cpiehl1, Charlotte Andersson @charlottea98   👍👍


yes: illustration, timing, loudly (very clear speech), readable,  technical (code),  originality, take-home

remarkable: motivation, reflection (excellent), technical


### DISTINCTION  DevOps in high security environments Isak Hassbring @hassbring, Gustaf Lidfeldt @glidfeldt  👍👍

yes: motivation, originality, loudly (very clear tone), engagement (pollev is original), readable, take-home, humour

remarkable:  illustration (multi layer of package manager, graphs), technical, reflection

Comments: grounded on sourced facts (equifax breach), actionable (npm retire); good references at the end which can also be put as footnote in slides

**Comment by monperrus** [comment]
# Presentations of week 5

### DISTINCTION Managing secrets in dynamic environments with HashiCorp Vault. Amar Hodzic @amarhod, Natan Teferi Asegehegn @callmeGoldenboy 👍👍

yes: timing, loudly (spreaks slowly and clearly), humour , 
readable, well-structured, technical,  take-home (actionabe)

remarkable: reflection, motivation, originality



### DISTINCTION DevSecOps takeaways from Hacking into Google's Network for $133,337 Ayub Atif @ayubatif 👍👍

yes: timing, illustration, well-structured, readable,  motivation, engagement (good story telling, energetic talk), humour (memes), take-home,

remarkable: originality, technical,  reflection (about the story, about bug bounties, about devsecops)

comments: credits and links are very good, be careful of not speaking too fast.


### DISTINCTION Flaky tests. August Jönsson @Augustjon, Daniel Grünler @grunler 👍👍

yes: timing, engagement (storytelling), readable,  humour (slide 9), loudly, illustration, technical

remarkable: motivation, well-structured, reflection



### PASS Kanban and Scrum. George Bassilious @George-Bassilious, Eva Despinoy  @evkade 👍

yes: timing, loudly, well-structured, motivation (clear definitions and relation to devops), reflection (good knowledge of the topic and differences / complementarities), readable

remarkable: illustration

comments: the links to source in every slide is excellent



### DISTINCTION Whitebox Fuzzing. Kitty Thai @kittytinythai, Sebastian Fagerlind @Sebberh 👍👍


yes: timing, originality, loudly, readable (beautiful slides), illustration, well-structured, reflection

remarkable: motivation (excellent problem statement), technical (snippets, SAGE), take-home (lessons of the day)

### PASS Devops with Tuleap. Vlado Mitrovic @vladomitrovic, Johan Mallo Bakken  @johanmallobakken 👍


yes: timing, illustration, motivation (agile needs alm), take-home, humour, readable, well-structured, reflection

remarkable: originality, engagement (live demo during Q&A)

**Comment by bbaudry** [comment]
# Presentations of week 6 

### DISTINCTION Modern end-to-end testing frameworks Agnes Petäjävaara @anorangesky, Adam Henriksson @adamih👍👍

yes: timing , loudly, readable, illustration, motivation (selenium is not enough anymore), well-structured, originality

remarkable: technical, engagement, reflection, take-home

Comment: we loved the voice-over code being written


### DISTINCTION CodeQL for automated code analysis. Axel Pettersson @Ackuq, Christopher Gustafson @ChristopherGustafson 👍👍

yes: timing, loudly, well-structured, motivation, readable, humour, take-home

remarkable: originality, technical, reflection

Comment: thank you for the [excellent curated list of tools](https://github.com/analysis-tools-dev/static-analysis)


### DISTINCTION Mobile backend as a service Lara Rostami @LaraRos, Christian Stjernberg @christian-stj 👍👍


yes: timing, reflection, readable, illustration, loudly, motivation,  loudly, well-structured, take-home

remarkable: originality, technical, engagement

Comment: we loved the firebase demo


###  PASS Maven and Gradle - The Battle of the Build Tools. Maja Tennander @majate, Axel Elmarsson @elmaxe 👍

yes: timing, illustration, readable, loudly, well-structured, take-home,  humour, technical

remarkable: engagement, motivation



### PASS Infrastructure automation using Ansible. Urama Ifeoma @IfyUrama, Yuxin Meng @yuxinmmmm 👍

yes: timing,  motivation, technical, well-structured, engagement, illustration, reflection

Comment: add slide numbers, avoid too much text on slides and don't forget a take-home message
