### ISSUE TITLE
Looking for essay partner week 3 - The inner workings of git

### ISSUE THREAD

**Issue by hallon-heyman** [KTH/devops-course#1089]
Hello, I would like to write an essay where we learn how git works within (beyond just branches) with its object model, I think it could be very relevant information to learn. 

This was my proposal for a presentation but they said it was fit for an essay so it should be good to be accepted.

You can contact me here, Hugo Heyman on facebook or hheyman@kth.se

**Comment by sestys** [comment]
Hey Hugo, this sounds interesting, I am down to join. I sent you an email, so we could discuss it more.
