### ISSUE TITLE
Open task: CI hackathon

### ISSUE THREAD

**Issue by bbaudry** [KTH/devops-course#118]
We have booked [R1](https://www.r1.kth.se/) on October 14 to organize a hackathon on CI vizualization
This will be in the context of the [CASTOR Software Days](https://castor-software-days-2019.github.io)

Interested in joining?

Please, get in touch!

**Comment by FelixEder** [comment]
@bbaudry does the hackathon have anything to do with the Open task of the course itself? Will participation/involvement count as doing an open task?

**Comment by bbaudry** [comment]
hi @FelixEder , yes an open task to prepare the hackathon can clearly count.
The idea of the hackathon is to visualize / sonify the Travis CI activity, live.
So, any activity that consists in preparing this hackathon would be a very good open task
Please, have a look at the API, the type of data that can be collected and suggest ideas about the artistic forms that can be used to 'embody' this data. You can discuss with @monperrus next Thursday

**Comment by FelixEder** [comment]
@monperrus @bbaudry we have added a PR #190 relating to this hackathon.

**Comment by monperrus** [comment]
See https://castor-software-days-2019.github.io/ci_art_hackathon for further update
