### ISSUE TITLE
Strict deadline for Video demo?

### ISSUE THREAD

**Issue by DSharifi** [KTH/devops-course#1210]
Is the strict deadline for video demos April 30, or May 31?

 I'm not sure what is meant by the description given in the README:
"The strict deadline for essays, tutorials, contributions to open-source, course automation is April 30, 23h59 Stockholm time; and "demo"; the strict deadline for repeated tasks (all) is May 31, 23h59 Stockholm time."

**Comment by Atema** [comment]
There's a (still semi-unclear) answer to this in the Google Doc: "Demos are due for the demo day", but also "After the demo day you will get some days to update your demo."

**Comment by majate** [comment]
My interpretation is that you need to submit a demo before the demo day during course week 7 (I guess it means the 11th of May). This demo will be presented during the demo day and you will get feedback by your peers. Afterwards you will get some days to resubmit your demo based on the feedback you got. The exact number of days for that resubmission is still unclear, but I guess they will give us that information closer to the demo day.

**Comment by bbaudry** [comment]
Yes, the deadline for demos is the demo day, on May 11, 9am CET, which is the lecture of week 7.
On that day, everyone (students and teachers) will look at the demos and provide feedback on the demo.
If you feel you want to improve the video, you will have until May 14 to submit an updated video.
Does this clarify?
