### ISSUE TITLE
Searching partner for GitLab Auto Devops demo 

### ISSUE THREAD

**Issue by Sjobom** [KTH/devops-course#123]
I am planning to set up a CD Pipeline that automatically build and test new changes and deploy them automatically after a review is approved.

The goal is to achieve this with the Auto Devops feature of GitLab and deploy tested and reviewed code to a Kubernetes cluster on the Google Kubernetes Engine.

This idea has already been accepted by the TAs [here](https://github.com/KTH/devops-course/blob/master/contributions/demo/asjobom/README.md).

**If you would like to do this together with me, you can contact me in this issue or by email [asjobom@kth.se](mailto:asjobom@kth.se).**

**Comment by felixkollin** [comment]
This sounds like an interesting demo idea, I would be interested in doing this with you if it's still possible.

**Comment by Sjobom** [comment]
Nice @felixkollin ! Let's do it together! I'll add your name to the folder.
