### ISSUE TITLE
[Stupid question] Understanding requirements for competition

### ISSUE THREAD

**Issue by juliuscc** [KTH/devops-course#154]
I and a couple of friends have difficulties understanding the statement: 

> All binaries are covered more than 0.75 * Average over all entries

Does this mean that you will gather the coverage from all submissions, average it, and fail all submissions that have worse coverage that 0.75*this average?

I first thought that our requirement was to achieve 75% test-coverage over the binaries.

**Comment by gluckzhang** [comment]
Hi @juliuscc , thanks for pointing this. I will double check with Martin and be back to you asap.

**Comment by gluckzhang** [comment]
Hi @juliuscc , actually here we want to set a threshold for students to pass the task. 0.75 is a fixed value which means the code coverage percentage on average. So your previous idea is correct, we calculate your submission's average score, which should be higher than 0.75 :)

**And after comparing with some novel research work on fuzz testing, we decide to adjust this value to 0.5.** I'll update the grading criteria page today. Let's keep this issue open for a while so that others could know the update.

Reference reading: [Coverage-based Greybox Fuzzing as Markov Chain](https://mboehme.github.io/paper/TSE18.pdf)

**Comment by juliuscc** [comment]
Okay that seams a lot more reasonable, especially as the reference you just sent is an experiment where three experienced researches as best achieved 76% statement coverage. Their execution environment is also very much different. As Klee and AFL(Fast) examine system properties/environment during execution, it is a lot easier to get coverage by running them on the same system that would be used for evaluation. We do not have this option as we have to precompile a list of inputs on an other environment. Even more significantly they ran their fuzzier for one hour per binary which effectively means that they had 20 times longer time than we will have.

I have a few other questions:

1. How will coverage be measured?
2. Which files will be included in the coverage calculation?

### How will coverage be measured?
Will the average be based on all executable lines vs all covered lines, or will it be based on averaging the coverage for all 20 binaries, independently of binary size?

Let's say we have 3 files:
- File A: **90% coverage**, File size is **10 lines**
- File B: **65% coverage**, File size is **10000 lines**
- File A: **70% coverage**, File size is **100 lines**

The average coverage *could be* 
```
(0.9 + 0.65 + 0.7) / 3 =
2.25 / 3 =
0.75
```

If you consider file size the average *could be*
```
((0.9 * 10) + (0.65 * 10000) + (0.7 * 100)) / (10 + 10000 + 100) =
(9 + 6500 + 70) / 10110 =
6579 / 10110 =
0.6507
```

Depending on how you calculate the coverage could be vastly different. I suggest that you calculate both and use the largest one. This is in my opinion fair as different groups might have used different methods for calculating coverage, and this would be not be unfair to any group that calculated the "*wrong way*". This could be more clear next year and you could use only one method that year.

### Which files will be included in the coverage calculation?

When I run `gcov cat` after executing my inputs I get the following output:

```
File '../src/cat.c'
Lines executed:72.41% of 232
Creating 'cat.c.gcov'
Cannot open source file ../src/cat.c

File '../src/ioblksize.h'
Lines executed:100.00% of 2
Creating 'ioblksize.h.gcov'
Cannot open source file ../src/ioblksize.h

File '../src/system.h'
Lines executed:96.00% of 25
Creating 'system.h.gcov'
Cannot open source file ../src/system.h
```

Will you only check `../src/cat.c` or will you also check `../src/ioblksize.h` and `../src/system.h`? The previous question is also relevant to how this coverage would be calculated.

**Comment by gluckzhang** [comment]
Hi @juliuscc , thanks, these are really good questions!

Your thought about file size is reasonable, we will calculate with and without considering file size and take the largest one. Next round we will also clarify this in the beginning.

Regarding files in the coverage calculation, we would like to simplify it: **only consider the key source file of the binary**. (For example, for `cat` we only calculate the coverage of `cat.c`, which provides the core functions of this binary.)

**Comment by gluckzhang** [comment]
Since the deadline has passed, close the issue now.
