### ISSUE TITLE
Fuzzing Challenge Submission Format

### ISSUE THREAD

**Issue by adamhass** [KTH/devops-course#155]
Hi!

Two questions regarding the format of the submission files we will hand in:
1. How (exactly) should test-cases be separated within the .txt files?
2. Should the .txt files be encoded somehow or just raw data?

**Comment by gluckzhang** [comment]
Hi @adamhass ,

> 1. How (exactly) should test-cases be separated within the .txt files?

Every fuzzed program should have a .txt file which contains a sequence of command arguments per line. If you need other files as parameters, you could put them into a `files` subfolder.

> 2. Should the .txt files be encoded somehow or just raw data?

For argument list files like `ls.txt`, they should be plain text files in utf-8. For other files you need to use as arguments, there is no restriction.

Reference: [submission format](https://github.com/KTH/devops-course/tree/master/contributions/competition#how-to-submit)

**Comment by juliuscc** [comment]
Are we allowed to include an image in the submission folder? This would allow us to create nicer Readme.md's.

**Comment by gluckzhang** [comment]
Hi @juliuscc , of course :)
You could put images into another subfolder like `doc`.

**Comment by juliuscc** [comment]
Great!

**Comment by gluckzhang** [comment]
Since the deadline has passed, close the issue now.
