### ISSUE TITLE
Check essay word count

### ISSUE THREAD

**Issue by halvtomat** [KTH/devops-course#1568]
I am currently working on a Github Action to check word counts in essays.

The working Github Action can be found here https://github.com/halvtomat/KTH-DevOps-EssayWordCounter.

_Originally posted by @monperrus in https://github.com/KTH/devops-course/issues/916#issuecomment-801790377_

**Comment by monperrus** [comment]
@halvtomat that's good, but you have to make sure to get an approval by the TAs before working on a task.
