### ISSUE TITLE
DUPLICATE Matchmaking 2022

### ISSUE THREAD

**Issue by monperrus** [KTH/devops-course#1569]
If you look for a teammate, post here.

**Comment by EDChui** [comment]
Hello! I am Edward. I am looking for a teammate for the upcoming tasks.
I am ok with any task (except essay, I don't prefer this task too much).
Email me at `myechui@kth.se` if you want to work together :).

**Comment by halvtomat** [comment]
Hello, **teammate wanted**

**Comment by abdelmoujibMegzari** [comment]
> Hello, **teammate wanted**

if you still need a teammate here is my email megzari@kth.se

**Comment by mrbgco** [comment]
Teammate bgeid@kth.se

Edit: Found for the first three tasks, if you are willing to collaborate for tasks 4, and 5 ( I am considering Demo, but open to other suggestions if you have a plan).

**Comment by LukasGutenberg** [comment]
Hello, teammate wanted

**Comment by EDChui** [comment]
Looking for teammate for "Open-source contributions" task.
Preferred language: Python, Java, C/C++

myechui@kth.se

**Comment by halvtomat** [comment]
Looking for teammate for Essay task.
My email is [danielg8@kth.se](mailto:danielg8@kth.se)

**Comment by Autonymic** [comment]
Looking for a teammate for essay task [ttle@kth.se](url)

**Comment by olofeldre** [comment]
Looking for teammate: Demo, feedback or katacoda for task 3 / 4. send me an email: olofgr@kth.se

**Comment by monperrus** [comment]
Duplicate of https://github.com/KTH/devops-course/issues/1166, closing and locking.

@abdelmoujibMegzari @mrbgco @Autonymic @olofeldre please post to https://github.com/KTH/devops-course/issues/1166
