### ISSUE TITLE
Contributing to Rust embedded development open source project

### ISSUE THREAD

**Issue by Dajamante** [KTH/devops-course#1585]
Hi,

I want to contribute to the Knurling project in the frame of this course. The Knurling project is an open source project to automate Rust Embedded development.
https://github.com/knurling-rs

For example `flip-link` offers stack protection by flipping the stack. When sensitive memory regions are reached, compilation fails instead of undefined behaviour: https://github.com/knurling-rs/flip-link.

`flip-link` needs some improvements: new parser to check that the `memory.x` file that describes memory regions is in the right format as well as support for arithmetic operations.

I thought this can fit nicely in CI/Testing as it automates tasks that were precedently done manually, i.e. a human should check if files were formatted correctly.

**Comment by cesarsotovalero** [comment]
Hi @Dajamante, 

The Knurling projects are excellent for the open-source contribution task.
Are you proposing adding new tests to flip-link, or setting up the CI pipeline?
Please be more specific when explaining your proposal 😄

**Comment by cesarsotovalero** [comment]
Oh, I just saw your PR https://github.com/KTH/devops-course/pull/1587.
Let's move this discussion there.
