### ISSUE TITLE
Distributed Tracing

### ISSUE THREAD

**Issue by nikentic** [KTH/devops-course#16]
**Example products**
* OpenTracing
* OpenZipkin
* Jaeger

> The ability to have this level of visibility is a true differentiator. It make your engineers happy and help them not burn out. This is how you scale in development and in production.

You can read more about this in this brilliant article: https://medium.com/@rakyll/cpdd-critical-path-driven-development-6c2592fb8ea4

**Comment by monperrus** [comment]
Merged with #8, thanks a lot for the suggestion.
