### ISSUE TITLE
Course Automation - Accessing previous years' contributions

### ISSUE THREAD

**Issue by Neproxx** [KTH/devops-course#1622]
For automating the similarity comparison of an assignment proposal with previous contributions we need to access the contributions of the previous years. We found that the attic folder contains all contributions for 2019 and 2020, but not for 2021. On the other hand, there are branches for 2020 and 2021 that contain the respective contributions, but there is no branch for 2019. We don't know if either of these findings is intended or not, but we would like to know against which contributions we should check for similarity (in order to simplify the TA's job of assessing whether the proposal is too similar).

**Comment by fsegatz** [comment]
Here is a link to the PR of the referred proposal: https://github.com/KTH/devops-course/pull/1586
