### ISSUE TITLE
Missing student registration :asim

### ISSUE THREAD

**Issue by landeholt** [KTH/devops-course#1634]
Missing student registration :asim

_Originally posted by @dd2482-bot in https://github.com/KTH/devops-course/issues/1629#issuecomment-1082834869_

Looks like Check task fails for the student asim, which I know takes this course stand-alone, and might therefore not have a kth-id (?)

**Comment by landeholt** [comment]
Student paulinev already registered for this task

_Originally posted by @dd2482-bot in https://github.com/KTH/devops-course/issues/1629#issuecomment-1084266767_

Now after 24h this is what I am getting. Pauline is asims presentation partner

**Comment by asja17** [comment]
This problem should have been solved. I wasn't previously registered in Ladok. But now I am.
