### ISSUE TITLE
Questions regarding task "feedback"

### ISSUE THREAD

**Issue by EDChui** [KTH/devops-course#1659]
Hello, I have questions regarding the task "feedback"

1.  In the grading criteria it states the following:
https://github.com/KTH/devops-course/blob/92564e16dc63b9e4282f54b41f6f6eec2e846bab/grading-criteria.md?plain=1#L161
From my understanding, it means that we should complete feedback for 1 "essay" **and** 1 "executable tutorial", 2 in feedbacks total, in order to get a pass in this task.
I would like to know if my understanding is correct, and shall I create separate pull requests for each feedback.

2.  As I would like to work on other things for my task 2 and 3, can I mark "feedback" as my task 4 or 5 even though the deadline of the essay/tutorial I would like to give feedback on ends before it?

3. Just out of curiosity, can "feedback" be a group task?

Thank you so much.

**Comment by nikolim** [comment]
@monperrus could you maybe quickly say some words about the task: feedback in class?

**Comment by monperrus** [comment]
Good question @EDChui.
 
We recall the feedback process:

1. Identify a task for which you'd like to give feedback
2. Register a feedback task as any other task via a pull-request
3. Talk with the authors of the targeted task to know when and how you'll get a proper version for feedback (not too drafty, still some time to handle the feedback)
4. Write the feedback as a PR comment, according to the feedback criteria https://github.com/KTH/devops-course/blob/2022/grading-criteria.md
