### ISSUE TITLE
Organizational challenges (Culture)

### ISSUE THREAD

**Issue by bittermandel** [KTH/devops-course#17]
The biggest challenge I see with DevOps is an organizational one. If a company did not start growing with a DevOps mindset, there's many challenges in changing methodology of an entire enterprise.

Quote from **Effective DevOps**:

> Ultimately, any "devops solution" that involves only tools while ignoring the _who_, _how_ and _why_ of tool usage within an organization is missing the big picture of what devops is about and why it can be so successful. Do not try to solve interpersonal and cultural problems solely with tools and technology.

How could this be discussed in a course format?

**Comment by monperrus** [comment]
Good point! Maybe a panel with 3-4 engineers commenting on their own experience?

**Comment by monperrus** [comment]
> DevOps is a mindset rather than a set of technologies.
>
I'm not sure about such a strong claim. DevOps means many different things for different people and
there is no consensus on a unique definition.

(Which makes it a powerful concept to my opinion).

**Comment by monperrus** [comment]
Open-question to address in the course: How does a [rubber duck](https://en.wikipedia.org/wiki/Rubber_duck_debugging) fit in the DevOps process?

**Comment by monperrus** [comment]
:) we'll see, DevOps is full of surprises.

**Comment by monperrus** [comment]
Merged with #7

**Comment by monperrus** [comment]
You can post/subscribe to #7
