### ISSUE TITLE
Choosing assignments 

### ISSUE THREAD

**Issue by saraersson** [KTH/devops-course#179]
Hi! I’m wondering if it’s OK to write essays both as ‘essay’ and ‘open’?

/ Sara

**Comment by gluckzhang** [comment]
Hi @saraersson , sorry for the late response.

I would say `open task` is more like a `development` or a `project`. So you should not register two essays. There are some registered open tasks [in the folder](https://github.com/KTH/devops-course/tree/master/contributions/open) which might bring you some inspiration :)
