### ISSUE TITLE
Repeated tasks 

### ISSUE THREAD

**Issue by Hasan-Kalzi** [KTH/devops-course#2025]
@javierron I did task 1 and 3 but I missed the deadlines for 2, 4 and 5. Can I do one of these task in repeated tasks to pass the course?

**Comment by javierron** [comment]
@Hasan-Kalzi You can submit the tasks by the 'repeat deadline' given that you have accepted proposal PRs for each task.

Please direct any other questions to [dd2482@eecs.kth.se](mailto:dd2482@eecs.kth.se).
