### ISSUE TITLE
Question about opensource contribution

### ISSUE THREAD

**Issue by JonathanArns** [KTH/devops-course#2090]
Do we need to specify beforehand, what exactly we would like to do or can we make it relatively vague for the opensource contribution, just mentioning the project?

I am asking since it might happen that we say we want to fix a specific issue and then that issue is fixed by someone else before we get the chance.

**Comment by javierron** [comment]
Hello, @JonathanArns 
Regarding questions about the tasks, please refer to the course's email; or open a PR, and we discuss there directly.
