### ISSUE TITLE
Looking for collaboration

### ISSUE THREAD

**Issue by Suvarchala1995** [KTH/devops-course#2097]
Hi Everyone, 

I'm searching for a collaborator to work with me on a _Presentation_ either during week3 or week4. Although I have some ideas regarding AWS for week4, I'm also willing to consider any suggestions you may have.

Thanks and regards
Suvarchala Jaldu

@jaldu@kth.se

**Comment by javierron** [comment]
Hello @Suvarchala1995 
Please post your comment on the corresponding issue: https://github.com/KTH/devops-course/issues/1166
