### ISSUE TITLE
Infrastructure as code

### ISSUE THREAD

**Issue by alanmcg** [KTH/devops-course#22]
Wikipedia page: https://en.wikipedia.org/wiki/Infrastructure_as_Code

Original comment:
As mentioned by someone in another ticket, infrastructure as code was the "next big thing" not long ago (it still is a big thing, but it's already here).

Terraform is the leader in this area with competitors such as AWS cloud formation.

"infra as code" comes with it's own issues, you can just as easily automate the total destruction of your production environment as you can create a new one if you are not careful. There is a lot of documentation and blog posts on using terraform etc, but they are typically a bit out of date. A devops course with a section on IAC would be awesome

**Comment by monperrus** [comment]
DNS (https://en.wikipedia.org/wiki/Domain_Name_System) is a key DevOps infrastructure (and that's the code service of Cloudflare)

**Comment by monperrus** [comment]
A Systematic Mapping Study of Infrastructure as Code Research
https://www.sciencedirect.com/science/article/pii/S0950584918302507

**Comment by bbaudry** [comment]
Terraform
https://www.terraform.io/

**Comment by bbaudry** [comment]
Infra as code
https://itnext.io/docker-makefile-x-ops-sharing-infra-as-code-parts-ea6fa0d22946

**Comment by monperrus** [comment]
Pets versus Cattle

Stop Killing Your Cattle: Server Infrastructure Advice
https://www.linuxjournal.com/content/stop-killing-your-cattle

**Comment by bbaudry** [comment]
Security Smells in Infrastructure as Code Scripts

https://arxiv.org/abs/1907.07159

**Comment by monperrus** [comment]
What about merging this thread into #2?

**Comment by monperrus** [comment]
Merged into #2
