### ISSUE TITLE
Michelin Devops Demo Day Schedule?

### ISSUE THREAD

**Issue by adamhass** [KTH/devops-course#242]
We would like to invite a guest for the MDDD and was wondering if it would be possible to get a schedule in advance of who will demo at what time?

If the schedule isn't ready yet or won't be released in advance, am I correct to assume there will be two groups of demos where group 1 demos 8-10 and group 2 demos 10-12?

**Comment by gluckzhang** [comment]
Hi @adamhass , the schedule in detail is not ready yet, but we will announce it this Thursday or Friday :)
There will be two sets of groups: 09:15-10:00, 10:15-11:00. Note that groups should come earlier and get everything ready before 09:15/10:00.

**Comment by gluckzhang** [comment]
Hi @adamhass , the schedule of MDDD has been announced [here](https://github.com/KTH/devops-course/blob/master/announcement/README.md). Cheers.

**Comment by monperrus** [comment]
Thanks all for this Great Michelin Devops Demo Day!

<img src="https://user-images.githubusercontent.com/803666/57965981-3084dd80-794c-11e9-9e0a-b7bee591ca21.jpeg"/>

<img src="https://user-images.githubusercontent.com/803666/57965982-34b0fb00-794c-11e9-86b5-eebc6c9ed6dd.jpeg"/>
