### ISSUE TITLE
Clarification on grading criteria 

### ISSUE THREAD

**Issue by jackma-00** [KTH/devops-course#2438]
Hello there, 

I wanted to request some clarification regarding the grading criteria for the scientific paper. Specifically, could you please explain what is meant by the term:

> **critical: The presentation contains a critical part**

Would it be possible to provide an example as well?

Thank you very much for the assistance.

**Comment by algomaster99** [comment]
Hi @jackma-00 ! It means finding limitations in their study. You should be able to explain both the good and the bad parts of the paper :)
