### ISSUE TITLE
CI job for live counting active participation

### ISSUE THREAD

**Issue by algomaster99** [KTH/devops-course#2459]
Hi all,

We are back with another idea for an open-source contribution. 

This year we introduced [active participation](https://github.com/KTH/devops-course/issues/2370) as one of the criteria for grades. Now, it's a CI course. We won't be counting who asked question in what lecture, right? Let's write a CI script in this repo and whoever does this will get an open source contribution task. Some checks we need to have:

1. Ignore comments by collaborators.
2. Ensure the comment is made on the right date and time of the lecture.
3. Ensure the comment contains the topic that the question is related to (optional)
4. Ensure the comment contains the answer to that question (optional)

Let's start with these criteria and maybe we evolve based on the different comments we see. :D 
@monperrus @sofiabobadilla @javierron @Deee92 Do you want to add more factors above?

**Comment by bjornthiberg** [comment]
I'm at home sick, so would like to work on this. Is it a race for who submits the first PR? 😜

**Comment by algomaster99** [comment]
Hi @bjornthiberg ! You won the race of taking up this issue :) It is all yours. Looking forward to a PR soon :D

**Comment by algomaster99** [comment]
@bjornthiberg Could you please submit the pull request for this task like you do for presentation, demo, etc? We need that to [enumerate tasks](https://github.com/KTH/devops-course/issues/2368) later.
