### ISSUE TITLE
Same group member for both presentation and demo

### ISSUE THREAD

**Issue by SKFrozenCloud** [KTH/devops-course#2462]
Are we allowed to work with the same person for both presentation and demo?

And then a different person for another task?

**Comment by sofiabobadilla** [comment]
Yes. 

Quote to the repository:
> Group work is encouraged (max 2 persons) but you cannot be with the same person for more than 2  tasks. As a general rule, you are not allowed to work alone.

https://github.com/KTH/devops-course/
