### ISSUE TITLE
Break CI if there are more than 1 file changes

### ISSUE THREAD

**Issue by algomaster99** [KTH/devops-course#2583]
Some PRs have more than 1 file change. Example: https://github.com/KTH/devops-course/pull/2552. The CI should break if this is the case.

Conditions:
* File changes should be exactly 1. Not sure if we should allow 0 file changes, but let's be strict.

EDIT: updated the list of conditions.

**Comment by RafDevX** [comment]
@ludvigch and I would like to work on this issue for our open source contribution. May we?

**Comment by algomaster99** [comment]
Go for it! Do submit a proposal PR as well.
