### ISSUE TITLE
Streamed guest lecture: "Massive-Scale QA for multi-player video games" (David King, Mark Baker) 

### ISSUE THREAD

**Issue by monperrus** [KTH/devops-course#286]
Monday 13 May 10h15 CET
Online talk: "Massive-Scale QA for multi-player video games"
Speakers: [David King](https://www.linkedin.com/in/david-king-83b9765b), [Mark Baker](https://www.linkedin.com/in/markltbaker/), [DICE](https://www.dice.se)
Streaming URL: <https://www.youtube.com/c/KTHMediaProduction/live>
IRL: [KTH U41](https://www.kth.se/places/room/id/bb4faf52-8ff1-40ae-8211-b73a54703b8d)
Talk URL: <https://github.com/KTH/devops-course/issues/286>

**Comment by gluckzhang** [comment]
The recorded video: [https://youtu.be/ffgphqKrb2M](https://youtu.be/ffgphqKrb2M)

**Comment by monperrus** [comment]
Thanks again Mark and David!

**Comment by monperrus** [comment]
<img src="https://user-images.githubusercontent.com/803666/57621321-6a8c6300-758b-11e9-94e3-c186b1a7b2f6.png"/>
