### ISSUE TITLE
Who is the author of the devops infinite loop picture?

### ISSUE THREAD

**Issue by monperrus** [KTH/devops-course#287]
Who is the person who did the very first DevOps picture using the infinity symbol?

https://www.google.com/search?tbm=isch&q=devops

**Comment by felixkollin** [comment]
The first occurrence I could find is by Dustin Whittle, 2013, in this blog post:
https://www.appdynamics.com/blog/engineering/devops-scares-me-part-2/

**Comment by monperrus** [comment]
And the legend explains the figure: "DevOps can create an infinite loop of release and feedback for all your code and deployment targets"

Maybe @dustinwhittle would have the definitive answer?

**Comment by cjlennon** [comment]
The picture is now a missing image lol
