### ISSUE TITLE
Assertion libraries

### ISSUE THREAD

**Issue by monperrus** [KTH/devops-course#305]

**Comment by monperrus** [comment]
https://junit.org/

**Comment by monperrus** [comment]
http://hamcrest.org/

**Comment by monperrus** [comment]
https://joel-costigliola.github.io/assertj/

**Comment by monperrus** [comment]
https://github.com/google/truth

**Comment by monperrus** [comment]
https://github.com/groupon/assertive

**Comment by bbaudry** [comment]
https://github.com/electronicarts/EAAssert

**Comment by monperrus** [comment]
PowerMock is a Java framework that allows you to unit test code normally regarded as untestable. 
https://github.com/powermock/powermock

**Comment by monperrus** [comment]
Chai is a BDD / TDD assertion library for node and the browser
https://www.chaijs.com/

**Comment by monperrus** [comment]
Spock is a testing and specification framework for Java and Groovy applications
http://spockframework.org/

**Comment by monperrus** [comment]
mockey: a simple and easy-to-use golang mock library
https://github.com/bytedance/mockey

**Comment by monperrus** [comment]
[Mimicking Production Behavior with Generated Mocks](http://arxiv.org/pdf/2208.01321)
