### ISSUE TITLE
Tags/Labels for issue organization

### ISSUE THREAD

**Issue by DokID** [KTH/devops-course#31]
If we are going to be using Github issues for topic suggestions, questions, discussions etc. then we should have tags to be able to filter these.

The tags I propose, and feel free to come up with more suggestions, are:

`Topic`: Used for topic suggestions, both from TA:s and students. Pretty self-explanatory.
`Question`: Used for asking questions that might interest a number of other students.
`"Stupid" Question`: For those that need a bit of insecurity in their lives 😛Otherwise, same as above.
`Discussion`: These might be topics that people would very much like to discuss with the rest of the class, perhaps a bit of cool tech or an interesting webinar. This tag should pretty much invite input and discussion (hence the name).

**Comment by slarse** [comment]
I think we need a `group swap` tag :)

**Comment by gluckzhang** [comment]
@DokID Hi, thanks for the suggestion. I have created more labels students might need. But it seems that only members who have write access to this repo are able to label issues. So feel free to open issues when you need, we will help to add labels later :)

**Comment by gluckzhang** [comment]
> I think we need a `group swap` tag :)

Hi @slarse , the initial groups are only suggestions now, you are free to reorganize your groups as along as it meets the updated rules: https://github.com/KTH/devops-course#group-rules
