### ISSUE TITLE
Remote participation Devops course 2020 - collecting remote participants

### ISSUE THREAD

**Issue by monperrus** [KTH/devops-course#314]
If you plan to attend the course remotely, drop your name and Github username in this thread.

**Comment by Paul-Philip** [comment]
Paul-Philip Mosulet
The username should show on the comment.
I should probably attend remotely the first week.

**Comment by htchan** [comment]
Name: Chan Ho Ting
User Name: htchan

**Comment by ashgreyship** [comment]
Name: Dingli Mao
User Name: ashgreyship

**Comment by hittesharma** [comment]
I would also like to know the same answer to this question asked by fellow student before giving my concent: 
Will lectures be streamed and/or available for on-demand playback? And if yes, will the setup allow for the lecturer themselves to be remote?

**Comment by christinasunnegardh** [comment]
Name: Christina Sunnegårdh
User Name: christinasunnegardh

Also planning to come to lectures, if nothing more happens regarding covid-19 or if I get sick myself.

**Comment by balwes** [comment]
Name: Balthazar West
Username: balwes

**Comment by shappe** [comment]
Name: Shapour Jahanshahi
Username: shappe

**Comment by eywoon** [comment]
Name: Eyrún Þrastardóttir
Username: eywoon

**Comment by louisezetterlund** [comment]
Name: Louise Zetterlund
Username: louisezetterlund

**Comment by johannaii** [comment]
Name: Johanna Iivanainen
Username: johannaii

**Comment by zen93** [comment]
Name: Akshay Sinha
Username: zen93

**Comment by klaraesr** [comment]
Name: Klara Eserstam
Username: klaraesr

**Comment by nagavem** [comment]
Name: Nagasudeep Vemula
Username: nagavem

**Comment by akhilyerrapragadaa** [comment]
Name: Akhil Y
Username: akhilyerrapragadaa

**Comment by christinerosquist** [comment]
Name: Christine Rosquist
Username: christinerosquist

**Comment by Callet91** [comment]
Name: Carl Jensen
Username: Callet91

**Comment by lehtihet** [comment]
Name: Oliver Schwalbe Lehtihet
User name: lehtihet

**Comment by emmariaolsson** [comment]
Name: Emma Olsson
Username: emmariaolsson

**Comment by gynther-k** [comment]
Name: Gunnar Applelid
Username: gynther-k

**Comment by JoarEkelund** [comment]
Name: Joar Ekelund
Username: JoarEkelund

**Comment by johansettlin** [comment]
Name: Johan Settlin
Username: johansettlin

**Comment by adbjo** [comment]
Name: Adam Björnberg
Username: adbjo

**Comment by MichaelaSahlgren** [comment]
Name: Michaela Sahlgren
Username: micsah

**Comment by sonderangebot10** [comment]
name: Justas Dautaras
username: sonderangebot10

**Comment by Mema5** [comment]
Name: Maël Madon
Username: Mema5

**Comment by krisgun** [comment]
Name: Kristoffer Gunnarsson
Username: krisgun

**Comment by ruwaid4** [comment]
Name: Ruwaid Louis
Username: ruwaid4

**Comment by stevensdavid** [comment]
Name: David Stevens
Username: stevensdavid

**Comment by JohanKJIP** [comment]
Name: Johan von Hacht
Username: johankjip

**Comment by SoFoDa** [comment]
Name: David Johansson
Username: SoFoDa

**Comment by rarkins** [comment]
Name: Rhys Arkins
Username: rarkins

**Comment by MindaugasVarkalys** [comment]
Name: Mindaugas Varkalys
Username: MindaugasVarkalys

**Comment by PaulLowenstrom** [comment]
Name: Paul Löwenström
Username: PaulLowenstrom

Might mix it up with remote and irl lectures

**Comment by valsen** [comment]
Name: Victor Josephson
Username: valsen

**Comment by Anthial** [comment]
Name: Sandro Lockwall Rhodin
Username: Anthial

**Comment by Gabbi68** [comment]
Name: Martin Gabrielsen
Username: gabbi68

**Comment by luic-c** [comment]
Name: Choy Louise Hui Ling
Username: luic-c

**Comment by emetha** [comment]
Name: Emelie Tham
Username: emetha

**Comment by jonasjohansson8908** [comment]
Name: Jonas Johansson
Username: jonasjohansson8908

**Comment by Pontus-Broberg** [comment]
Name: Pontus Broberg
Username: Pontus-Broberg

**Comment by cevataykans** [comment]
Name: Cevat Aykan Sevinc
Username: cevataykans

**Comment by keivanm** [comment]
Name: Keivan Matinzadeh
Username: keivanm

**Comment by georgewbar** [comment]
Name: George Rezkalla
Username: georgewbar

**Comment by sashikanthr** [comment]
Name: Sashikanth Raavikanti
Username: sashikanthr

**Comment by jzafar** [comment]
Name: Muhammad Jahangir Zafar
Username: jzafar

**Comment by cwinge** [comment]
Name: Christer Winge
Username: cwinge

**Comment by Nick-Steele** [comment]
Name: Nicholas Steele 
Username: Nick-Steele

**Comment by muachilin** [comment]
Name: Meng-Jin Lin
Username: muachilin

**Comment by jvikstrom** [comment]
Name: Johan Vikström
Username: jvikstrom
