### ISSUE TITLE
Streaming urls of lectures

### ISSUE THREAD

**Issue by monperrus** [KTH/devops-course#316]
We will post the streaming URLs 5 minutes before the lecture.

**Comment by monperrus** [comment]
Zoom URL for March 17 2020: https://kth-se.zoom.us/j/907394803

**Comment by SophieHYe** [comment]
Zoom URL for March 24 2020: https://kth-se.zoom.us/j/971558558

**Comment by SophieHYe** [comment]
Zoom URL for March 31 2020: https://kth-se.zoom.us/j/534118204

**Comment by SophieHYe** [comment]
Zoom URL for April 7th, 2020 (Week 4): https://kth-se.zoom.us/j/862680465

**Comment by SophieHYe** [comment]
Zoom URL for April 21st, 2020 (Week 5): https://kth-se.zoom.us/j/63877067970

**Comment by SophieHYe** [comment]
Zoom URL for April 28th, 2020(Week 6): https://kth-se.zoom.us/j/69999518970

**Comment by SophieHYe** [comment]
Zoom URL for May 5th, 2020(Week 7): https://kth-se.zoom.us/j/68637616036

**Comment by SophieHYe** [comment]
Zoom URL for May 12th, 2020(Week 8):  https://kth-se.zoom.us/j/61262805081

**Comment by monperrus** [comment]
March 23 2021: https://kth-se.zoom.us/j/62331342060*
![signal-2021-03-30-092448_001](https://user-images.githubusercontent.com/803666/112949838-2e376100-9129-11eb-9c57-f5c14eef4d14.jpeg)

**Comment by monperrus** [comment]
March 30 2021
![signal-2021-03-30-092448_002](https://user-images.githubusercontent.com/803666/112949936-40b19a80-9129-11eb-9190-9d2602aef397.jpeg)

**Comment by monperrus** [comment]
the 2022 edition is on campus.
