### ISSUE TITLE
How to book zoom meetings for labs?

### ISSUE THREAD

**Issue by georgewbar** [KTH/devops-course#319]
I can not find information about booking zoom meetings for the labs. Where can I find them?

Thanks!

**Comment by gluckzhang** [comment]
Hi @georgewbar , thanks for creating this issue! Based on @SophieHYe 's comment on zoom, I propose to do it in this way:
- During the planned lab time slot, it's recommended to use [the queue](http://queue.csc.kth.se/#/queue/DD2482) for booking meetings
- Put your zoom meeting link (or other platforms like Skype / GoogleHanouts) in the queue
- One of our TA will reach you asap

What do you think? I will document this later in the main README.md :)

**Comment by georgewbar** [comment]
Sounds good. Thanks for the answer!

**Comment by gluckzhang** [comment]
Solution documented.
