### ISSUE TITLE
Team member needed 

### ISSUE THREAD

**Issue by eywoon** [KTH/devops-course#322]
Hi everyone
I'm looking for a team member 😀
My interests are in serverless things, distributed things, big data testing, docker and would happily work with Google cloud. 
I am also open to try something completely different.

I work full time so I'll mostly be available in the evenings/weekends but with some flexibility of course.

I aim for at least passing grade but am also very happy to aim higher 🤓

-Eyrún

**Comment by Paul-Philip** [comment]
Hi Eyrún!

I'm interested in working together! I'm basically fine with trying out anything! 
I also work so would be a good match for me with regards to that.

/ Paul-Philip

**Comment by eywoon** [comment]
Amazing! 
What is you're preferred communication tool so we could sync up :) ?

**Comment by Paul-Philip** [comment]
I mostly use FB-messenger, but could do whatsapp or anything else.
My full name: Paul-Philip Mosulet
Phone: +46720849925

**Comment by zen93** [comment]
Hey Eywoon,
I am also interested in Docker and serverless things. Room for one more?

**Comment by Paul-Philip** [comment]
If we find a 4th member we could rotate after completing 2 tasks @zen93, @eywoon?

**Comment by gluckzhang** [comment]
Hi @eywoon , I am organizing the open issues. If you have found team members, please consider closing the issue. Thanks :)
