### ISSUE TITLE
Looking for a teammate!

### ISSUE THREAD

**Issue by pojans** [KTH/devops-course#323]
Lets discuss expectations and goals before committing.

**Comment by zen93** [comment]
Hi, I am interested in Docker, Kubernetes, CI/CD pipelines (any technology used in industry is fine with me), Microservices architecture, Serverless and Infrastructure as a code. These are my main interests but I'm open to suggestions too.

**Comment by pojans** [comment]
Hi, we seem to share the common interest for kubernetes, lets meet up in the back of the classroom and discuss.

**Comment by zen93** [comment]
I'm doing the lectures remotely. Maybe you can call me? My number is +46793465661

**Comment by AviRoy1988** [comment]
I am interested for kubernetes too and have some experience with docker and devops tools. Do you have place for one more ?

**Comment by pojans** [comment]
Sure, how about you send me your kth email and I will contact you asap.
