### ISSUE TITLE
Looking for a team member

### ISSUE THREAD

**Issue by Volminger** [KTH/devops-course#325]
Hi!
I am also looking for a team member :smiley:

I am interested in learning more about chaos engineering and micro services in general. But I am of course open to working on other topics as well :blush:
I have some previous experience with Infrastructure as code, Serverless, AWS and Slack bots. 

 Aiming for a higher grade in the course :nerd_face: I speak Swedish and English, so just hit me up if you are interested

**Comment by cevataykans** [comment]
Hey, I have no prior experience with chaos engineering and micro services but would love to learn!

**Comment by Volminger** [comment]
Then we are on the same level! :blush: I will add you on messenger, let's continue talking there

**Comment by EyuTes** [comment]
I am interested for CI/CD pipelines, docker and micro-services. If you need one more person you can contact me at eyueltb@gmail.com

**Comment by hittesharma** [comment]
Hi, 
I was looking for a person having prior experience in these fields. I have in it too. May be we can be a good team, aiming for distinction. Let’s have a short call to discuss first, if you like.

**Comment by EyuTes** [comment]
Hi,
I am interested for the topics like CI-CD pipe line, docker, micro-services
and others. My aim is to know more and get a good technical skill on
topics  but i don't have a plan for
distinction  and if you are interested let start early on the topic you are
interested in.

Regards/Eyuel

**Comment by EyuTes** [comment]
I have a prior knowledge on 1. large-scale software testing and challenges in relation to quality attributes 2. i have a basic knowledge on docker but i can read 3. i have a testing knowledge

**Comment by Volminger** [comment]
Hey guys,
I already found a team member for all of the tasks. But I hope you will be able to find someone to work with :blush:

**Comment by gluckzhang** [comment]
Hi @Volminger , I am organizing the open issues. If you have found team members, please consider closing the issue. Thanks :)
