### ISSUE TITLE
Looking for a teammate

### ISSUE THREAD

**Issue by Mema5** [KTH/devops-course#326]
Hey!
I'm looking for a teammate. I don't have any specific idea for a topic right now, I will have to read more on everything. I speak English, French and better and better Swedish :p
Not particularly looking for the best grade everywhere, but interested to learn stuff :)
Do not hesitate to hit me up here!

**Comment by valsen** [comment]
Hey!

**Comment by Callet91** [comment]
The same for me. I study the Mechatronics-master and I´m open to anything basically. New to DevOps but have had courses that covered TDD (test driven development). I speak English and Swedish and I´m really good at making presentations.

**Comment by Mema5** [comment]
@valsen you were first. Do you want to call or something to talk?

**Comment by valsen** [comment]
@Mema5 Absolutely, my number is 0729799133, available whenever you are!
