### ISSUE TITLE
Looking for a teammate

### ISSUE THREAD

**Issue by ashgreyship** [KTH/devops-course#327]
I'm interested in Continuous integration and Continuous deployment / delivery / pipelines. I also consider Serverless computing. My plan is to learn several tools which are related to those topics for doing the projects.

**Comment by zen93** [comment]
Hi,
I am also interested in CI/CD pipelines and serverless computing. I am doing a demo in Kubernetes so for the rest of the categories I'm available. Would you like to collaborate on something?

**Comment by ashgreyship** [comment]
Sounds good! We can do the presentation and tutorial together.

**Comment by ashgreyship** [comment]
This is my email address, dingli@kth.se. Please send me an email if you are interested in above topics. I'm open to the other similar topics as well. Just send me an email and we can discuss more!

**Comment by AviRoy1988** [comment]
I am interested for CI/CD pipelines and different tools for that. Do you have another place to join? @zen93 I would like to do some demo on kubernetes. Let me know if we can team up for this.

**Comment by zen93** [comment]
@AviRoy1988 I am asking my teammate if he's okay with you joining the demo. I will let you know!

**Comment by zen93** [comment]
@AviRoy1988 Can I have your email we are on slack, I will ask him to add you onto there

**Comment by AviRoy1988** [comment]
its avi_roy1988@hotmail.com

**Comment by EyuTes** [comment]
I am interested for CI/CD pipelines, docker and serverless computing. If you need one more person you can contact me at eyueltb@gmail.com

**Comment by gluckzhang** [comment]
Hi @ashgreyship , I am organizing the open issues. If you have found team members, please consider closing the issue. Thanks :)
