### ISSUE TITLE
Looking for a teammate

### ISSUE THREAD

**Issue by Callet91** [KTH/devops-course#328]
Hi there! 

Looking for a teammate. I study the Mechatronics-master and I´m open to anything. A bit new to DevOps but have had courses that covered TDD (test driven development). I speak English and Swedish and I´m really good at making presentations. :) 

For a brief overview of me check my portfolio/application page I did for this years summer internship scouting: 

https://carljensen.io/

I really want to get out as much as possible from this course since I´m going to work partly with DevOps this summer. 

I´m easy to work with and a teamplayer.

**Comment by Volminger** [comment]
Hey there! :smiley:
I probably already have one person to work with on 2 of the projects. But I am open on working with you on the other projects :blush: Maybe we can do the presentation together?

**Comment by Callet91** [comment]
Sounds great Volminger :)

**Comment by zen93** [comment]
Hey I have one person to work with me currently on 1 project. I'm looking for partners on 3 other projects. I am doing a demo on Kubernetes so I'm available for other categories and topics.

**Comment by Callet91** [comment]
@zen93 Great, as I said, I´m up for anything as well. My plan now is to read through the various topics and get an idea of them. I´m having a discussion with @xmas92 in another issue. Maybe we can coordinate something all three of us and have a zoom meeting later this evening?

**Comment by zen93** [comment]
@Callet91 I am likely to do a presentation and tutorial with someone else. But am willing to collaborate on an essay (open to topics). Is that something you would like to do as well?

**Comment by Callet91** [comment]
That sounds good :) Do you want to join in a Zoom chat later today? Around 7 pm?

**Comment by zen93** [comment]
Sure, I am available.

**Comment by Volminger** [comment]
> Sounds great Volminger :). Have you already fixed someone for the first PR?

I am still not sure what I will do my first PR in, need to coordinate a bit with my other teammate on that :) Do you have Messenger or a number, so we can continue chatting on that?

**Comment by Callet91** [comment]
@Volminger Yes, Calle Jensen on facebook would be preferred :)

**Comment by Callet91** [comment]
> Sure, I am available.

Nice!

**Comment by axelkennedal** [comment]
Please close this issue if you have already found teammates
