### ISSUE TITLE
Looking for a teammate

### ISSUE THREAD

**Issue by xmas92** [KTH/devops-course#332]
I am looking for a teammate for a first task.
I have very little prior experience with DevOps. I have another lecture now so won't be able to work on anything until tonight. My plan is to spend my evening reading through all the topics trying to find something that feel interesting. I am open to anything.

So if anyone wants to collaborate and try to find some initial task feel welcome to respond, (or someone that already has a topic and task in mind but wants someone to collaborate with).

**Comment by Callet91** [comment]
Hi!

**Comment by xmas92** [comment]
Hey. 
I saw that you might be working with @Volminger but see now that that is for the later tasks. 
Have any idea what you want to work on as a first task? (Maybe you need to coordinate with @Volminger so we do not clash)

Is there any specific area of DevOps you want to work with? 
You mention that you are going to work some DevOps this summer, maybe if you know what it is about it would be a good area to start from?

**Comment by Callet91** [comment]
Yeah, I need to check with him for the presentation. Also, i feel like I need to read through the various topics. But how about i read through the topics and we can book a Zoom meeting after your lecture?

**Comment by xmas92** [comment]
I wont be home until 18:00 and will probably need to make something to eat then. I can be available at 19:00. 
I also have around an hour right now befor my lecture at 15:00 (I am currently browsing different topics)

**Comment by Callet91** [comment]
Nice! Let us aim for 19:00 since I need to eat something now :)

**Comment by Callet91** [comment]
You can add me on facebook if you like @xmas92. My name there is Calle Jensen

**Comment by gluckzhang** [comment]
Hi @xmas92 , I am organizing the open issues. If you have found team members, please consider closing the issue. Thanks :)

**Comment by xmas92** [comment]
I have two registered tasks, and a group that is working on a third. So technically I could still use a team for a fourth task. However this issue does not contain that up to date information so I might as well close it. Might just do the last task alone, or open up a new issue with more specific information.
