### ISSUE TITLE
Looking for group member(s)

### ISSUE THREAD

**Issue by jadlers** [KTH/devops-course#339]
Hi!

I'm planning to complete four out of the following categories:  presentation, demo, tutorial, competition entry, contribution to open-source. I have already planned to hold a presentation on [configuration management with Ansible](https://github.com/KTH/devops-course/pull/335). Join in if you want, I don't have any prior knowledge about it. As for the other categories, I'm not sure about a topic yet.

I've worked a bit with Docker and Kubernetes seems very interesting. I do like automating various tasks and have an interest in smart home automation. Microservices are also an interesting topic but I'm very open to suggestions for other topics as well!

With the limit of two categories per pair, I'm looking for two collaborators. Let me know if you're interested!

**Comment by valsen** [comment]
I'm interested in automation and smart homes too, and looking for a collaborator for tutorial and either the competition or open-source contribution. Wanna team up either of those?:)

**Comment by jadlers** [comment]
@valsen Sure thing, would be cool if we could find some open source project connected to smart homes!

**Comment by jadlers** [comment]
@valsen Would you like to discuss ideas this afternoon or tomorrow? You could send me an email at jadlers@kth.se to discuss further
