### ISSUE TITLE
Is it allowed to create a new open-source project?

### ISSUE THREAD

**Issue by georgewbar** [KTH/devops-course#348]
For the open source project, is it allowed to create a totally open-source project? or is it only allowed to contribute to an already existing one? According to the criteria for the open-source project, it is only allowed to contribute to an already existing one.

**Comment by gluckzhang** [comment]
Hi @georgewbar , this was discussed during today's lecture. You are welcome to propose a new open-source project and discuss if it meets the criteria with @monperrus and @bbaudry :)

**Comment by georgewbar** [comment]
Thanks for the answer!

**Comment by gluckzhang** [comment]
The question has been answered. Closed.
