### ISSUE TITLE
Looking for a team member for Essay/ Tutorial

### ISSUE THREAD

**Issue by hittesharma** [KTH/devops-course#358]
Hi,
I am looking out for someone with basic understanding of CI/CD operations or good in coding & testing and interested to explore DevOps. I have some knowledge of DevOps in general and could guide you through basics but planning to share skills with someone who have a basic idea of pipelines or Azure or build & deploy or excellent in describing the concept on paper. Otherwise, if you have some simple code and test cases ready then I would guide you about the rest of the DevOps concepts and take care of that part.

I want to complete it as soon as possible. I am targeting “distinction”. Please comment if you have the similar passion!

**Comment by axelkennedal** [comment]
Hi, I'd be interested in teaming up :) I recently finished a course where me and my team implemented our own CI server. I work 50% of my time as a software engineer, with Azure Devops at work.

**Comment by hittesharma** [comment]
Awesome, you can reach me on hiteshs@kth.se/ hitesh.sharma@ercisson.com

**Comment by EyuTes** [comment]
Here i am also looking for a team CI/CD, DevOps, and micro-services you can add me if you are interested.

**Comment by hittesharma** [comment]
> Hi, I'd be interested in teaming up :) I recently finished a course where me and my team implemented our own CI server. I work 50% of my time as a software engineer, with Azure Devops at work.

I am waiting for your mail. I wish to complete work soon. Let me know if you are still interested to team up otherwise I will start now.
hiteshsharma.edu@gmail.com

**Comment by hittesharma** [comment]
> Here i am also looking for a team CI/CD, DevOps, and micro-services you can add me if you are interested. [eyueltb@gmail.com](mailto:eyueltb@gmail.com)

Mailed you!

**Comment by EyuTes** [comment]
HELLO,

Yes we can do that. Let us talk

Regards/Eyuel

**Comment by hittesharma** [comment]
**I am still looking for anyone interested to work on the essay and/or Presentation !** 
However, our Team has been created for Tutorial.

**Comment by sujon2100** [comment]
> **I am still looking for anyone interested to work on the essay and/or Presentation !**
> However, our Team has been created for Tutorial.

I can be with you for the presentation/essay .)

**Comment by gluckzhang** [comment]
Hi @hittesharma , I am organizing the open issues. If you have found team members, please consider closing the issue. Thanks :)

**Comment by hittesharma** [comment]
I am proceeding without team on presentation now. Closing this issue.
