### ISSUE TITLE
Group update

### ISSUE THREAD

**Issue by junglebooboo** [KTH/devops-course#36]
Adam Hasselberg @adamhass (adamhas@kth.se) and Aigars Tumanis (tumanis@kth.se) would like to create a group for Task1:Presentation for week 2 and Task4:Demo.

**Comment by junglebooboo** [comment]
@adamhass

**Comment by gluckzhang** [comment]
Hi, since the group rules [has been updated](https://github.com/KTH/devops-course#group-rules), I'll close this issue now :)
