### ISSUE TITLE
Presentation deadline

### ISSUE THREAD

**Issue by axelkennedal** [KTH/devops-course#366]
Is the deadline for the presentation also April 30 2020, 23h59 Stockholm time? It is not mentioned in the README.

**Comment by gluckzhang** [comment]
Hi @axelkennedal , since all presentations are done during the lecture. The deadlines are different according to the week you are going to present. Thus the last opporunity for a presentation is `Week 6 April 28` :)

**Comment by gluckzhang** [comment]
The question has been answered. Issue closed.
