### ISSUE TITLE
Looking for a teammate 

### ISSUE THREAD

**Issue by keivanm** [KTH/devops-course#371]
Hi! I am looking for a teammate! What kind of topic don't really matter to me. I do have some experience working with devops :)

**Comment by GustavDowling** [comment]
Hi, do you want to do the fuzzing competition with me and a tutorial or essay on some topic? 

So far microservices is a topic i'd like to explore further, A/B testing and how it is used is also very fascinating.

You can contact me on facebook Gustav Dowling or if you're not on there email me at gdowling@kth.se

**Comment by keivanm** [comment]
> Hi, do you want to do the fuzzing competition with me and a tutorial or essay on some topic?
> 
> So far microservices is a topic i'd like to explore further, A/B testing and how it is used is also very fascinating.
> 
> You can contact me on facebook Gustav Dowling or if you're not on there email me at [gdowling@kth.se](mailto:gdowling@kth.se)

I'll message you on facebook!

**Comment by hittesharma** [comment]
Hi,
Are you looking for a partner in a presentation or Essay? If yes, then let me know, I am searching for one.

**Comment by gluckzhang** [comment]
Hi @keivanm , I am organizing the open issues. If you have found team members, please consider closing the issue. Thanks :)
