### ISSUE TITLE
Regarding originality

### ISSUE THREAD

**Issue by georgewbar** [KTH/devops-course#380]
I see that in some PRs, the originaility of presentation, essay, tutorial, etc, is taken up. However, as i understand it now, the criteria for pass/pass with distinction for each category is different and it may be not required to be original to pass/pass with distinction.

For example, in presentation category, there are 13 grading criteria, and one of them is: "The presentation contains one part that is original". However, to pass, only 7 out of 13 criteria are needed for a pass. Therefore, it is not required to be original to pass presentation category as long as 7 out of the rest of the grading criteria are passed. To pass with distinction, one needs at least 3 "remarkable". Same reasoning holds for other categories that allow for that.

Did i understand the grading system right?

**Comment by gluckzhang** [comment]
Hi @georgewbar , thanks for raising this question!
We could consider `originality` in different aspects:

- new ideas about the technical part, like how to apply an existing tool to solve new problems / how to improve the CI/CD pipeline by using containers, etc.
- the empirical studies on existing techniques, like a comparision between different CI platforms
- the way you introduce the topic, like how you interact with the audience, a scenario-based tutorial

Based on the background of your study, some of the aspects may be difficult to achieve. But of course, there's no need to meet all the points. When we review a PR, we would like to remind that students should not pick up a single entry from the Internet and just repeat what they read there. Thus we emphasize more on the originality and reflections.

It's fine to focus on different grading criteria. But we still encourage students to learn and think more in the world of DevOps. Hopefully this answers your question :)

**Comment by georgewbar** [comment]
I think i understand now. So, in most cases, the idea is more about reading from different resources and reflections on them and trying to connect the dots between material. Is that right?

**Comment by gluckzhang** [comment]
> I think i understand now. So, in most cases, the idea is more about reading from different resources and reflections on them and trying to connect the dots between material. Is that right?

This is only one aspect of originality (e.g., the comparison and reflection part). Because you could certainly go for other directions like new tool development, a new combination of existing tools. Even if you read only one article, you have a good reflection or constructive suggestions to improve the idea, it counts as original content :)

**Comment by georgewbar** [comment]
Understood. Thanks a lot!

**Comment by gluckzhang** [comment]
The question has been answered. Issue closed.
