### ISSUE TITLE
Question regarding our presentation about Travis vs Jenkins 

### ISSUE THREAD

**Issue by Marcus9512** [KTH/devops-course#381]
Hello, we asked a question regarding PR #342 , however the PR is closed so we suspect that no TA was notified about it. We would appreciate if someone took a look at our suggestion.

**Comment by gluckzhang** [comment]
Hi @Marcus9512 , I just left some comments on your PR. Since @SophieHYe is reviewing it, I also pinged her to ask for some comments :)
