### ISSUE TITLE
Looking for a teammate to do the tutorial with

### ISSUE THREAD

**Issue by Callet91** [KTH/devops-course#383]
Hi again! 

Looking for a teammate to do the tutorial with. 

Topics I have covered: 
- Regression testing
- CD/CI 

Up for anything!

**Comment by jadlers** [comment]
Hi!

I'm looking to do a tutorial as well. I haven't got a clear topic in mind but kubernetes and microservices are two areas which I'm interested in. Open for other ideas though!

**Comment by Callet91** [comment]
> Hi!
> 
> I'm looking to do a tutorial as well. I haven't got a clear topic in mind but kubernetes and microservices are two areas which I'm interested in. Open for other ideas though!

Sounds perfect to me! I want to learn more about microservices and kubernetes so that would be awesome! Do you have Facebook?

**Comment by jadlers** [comment]
> Do you have Facebook?

I do, go ahead and add me "Jacob Adlers"
