### ISSUE TITLE
Rules for remote participation due to covid-19 situation

### ISSUE THREAD

**Issue by Mema5** [KTH/devops-course#391]
Hi, 

I don't really understand the rules for remote participation updated by @monperrus a few days ago in the main README (commit 7ef023d). It was before the announcement of KTH closing down.

In particular, what does this sentence mean:

`"presentation": there is no online version of the presentation task`

How is it going to be handled during next lecture?

Thank you for your answer.

**Comment by monperrus** [comment]
> It was before the announcement of KTH closing down.

Indeed.

We'll have to hold online presentations, and all together, we'll find ways to make this engaging and productive.

**Comment by gluckzhang** [comment]
Online presentations seem to work fine so far. I will close this issue.
