### ISSUE TITLE
Looking for teammate

### ISSUE THREAD

**Issue by adbjo** [KTH/devops-course#394]
Hello!
I'm looking for a teammate for essay/tutorial/demo/open-source/competition.
I have some experience with CI from the software engineering fundamentals course.
Interested in any topic! 👨‍🔬

Mail: adambjo@kth.se
Facebook: /adambjornb

**Comment by hittesharma** [comment]
Hi,
Are you looking for a partner in a presentation and/or Essay? If yes, then let me know, I am searching for one.

**Comment by adbjo** [comment]
> Hi,
> Are you looking for a partner in a presentation and/or Essay? If yes, then let me know, I am searching for one.
> [hiteshs@kth.se](mailto:hiteshs@kth.se) - Just drop me a mail if interested.

Mailed you!

**Comment by gluckzhang** [comment]
Hi @adbjo , I am organizing the open issues. If you have found team members, please consider closing the issue. Thanks :)

**Comment by adbjo** [comment]
May need a teammate in the future. I'll close this for now :)

**Comment by gluckzhang** [comment]
@adbjo , thanks. Feel free to reopen it or create a new issue :)
