### ISSUE TITLE
Artifact repositories

### ISSUE THREAD

**Issue by GoranPaues** [KTH/devops-course#4]
Built versions of applications need to be stored in some kind of artifact repository, from where they can be downloaded and installed. 
Examples of solutions here are Artifactory and Nexus.

**Comment by goranpaues-tradedoubler** [comment]
Yes, a repository like Artifactory is what I meant. To me, it's a file storage server with practical features like versioning, retention policies and licensing control. In the Java world, it is common to use Gradle or Maven scripts to build an application. In those scripts, any dependent libraries or components (artifacts!) will then be retrieved from the repository in a standarized way when the application is built.

**Comment by monperrus** [comment]
+1 for  licensing control

**Comment by monperrus** [comment]
Merged with #24 

Thanks again @GoranPaues
