### ISSUE TITLE
ATDD vs TDD literature

### ISSUE THREAD

**Issue by balwes** [KTH/devops-course#407]
Hi, my group will do a presentation comparing ATDD and TDD. While there already is material on this repo, if anyone knows of more sources feel free to link them here.

**Comment by gluckzhang** [comment]
Hi, these two articles may be helpful :)

- https://www.browserstack.com/guide/tdd-vs-bdd-vs-atdd  
- https://www.softwaretestinghelp.com/testers-in-tdd-bdd-atdd-techniques/
