### ISSUE TITLE
Group Update

### ISSUE THREAD

**Issue by hannesrabo** [KTH/devops-course#41]
We are four people who want to change the proposed groups for all the tasks.

These are the newly proposed groups:

T1: Hannes Rabo <hrabo@kth.se>, Julius Celik <jcelik@kth.se>
T1: Patric Ridell <pridell@kth.se>, Daniel Karlsson <dka4@kth.se>

T2: Hannes Rabo <hrabo@kth.se>, Julius Celik <jcelik@kth.se>
T2: Patric Ridell <pridell@kth.se>, Daniel Karlsson <dka4@kth.se>

T3: Hannes Rabo <hrabo@kth.se>, Daniel Karlsson <dka4@kth.se>
T3: Patric Ridell <pridell@kth.se>, Julius Celik <jcelik@kth.se>

T4: Hannes Rabo <hrabo@kth.se>, Daniel Karlsson <dka4@kth.se>
T4: Patric Ridell <pridell@kth.se>, Julius Celik <jcelik@kth.se>

// Hannes

**Comment by juliuscc** [comment]
I (Julius) approve

**Comment by SophieHYe** [comment]
hi, we no longer maintain the group number anymore, see the announcement here. https://github.com/KTH/devops-course/tree/master/announcement. So I will close this issue soon if everyone is happy with the current rule.
