### ISSUE TITLE
Add Labels for Task Categories, Topic Proposals and Finished Tasks

### ISSUE THREAD

**Issue by shappe** [KTH/devops-course#410]
I want to suggest using a system of Labels for Issues & Pull Requests in this repo:

- Labeling Issues & PRs related to the different tasks with a category label (e.g. **Presentation**, **Tutorial**, **Demo**, etc)
- Labeling PRs with Topic Proposals as **Proposal** or something similar.
- Labeling PRs with Finished tasks as **Completed** or something similar.

This would make it easier for everyone to filter the vast ocean of topics in the course repo.
I think my suggestion above can be improved but you get the general idea! :smile:

**Comment by gluckzhang** [comment]
@shappe Great idea, thanks! I will do that manually for now. Later when I have time, hopefully we could set up a GitHub action do support this :)

**Comment by gluckzhang** [comment]
The work is partially done (all of the PRs in this round have been labeled). I will close this issue first.
Hopefully, we will set up an action to automatically label issues and PRs in the future.
Thanks again!
