### ISSUE TITLE
Add requirements for Passing (with/without distinction) to the Essay task.

### ISSUE THREAD

**Issue by shappe** [KTH/devops-course#415]
The [Essay page](https://github.com/KTH/devops-course/tree/master/contributions/essay) README doesn't include the number of grading criteria that must be fulfilled to receive a Pass or Pass with Distinction for the task.

Would you please consider adding this? It would help us understand the scope of the essay.

**Comment by gluckzhang** [comment]
@shappe , thanks for pointing this out. We will fix this asap :)

**Comment by monperrus** [comment]
thanks for the bug report.

closed per #421
