### ISSUE TITLE
Looking for a teammate

### ISSUE THREAD

**Issue by sujon2100** [KTH/devops-course#420]
Hi, 

I am looking for a teammate for the presentation, demo, essay, Covid19?
email: mhud@kth.se

**Comment by sashikanthr** [comment]
Hi,

May I know if you are still looking for a team mate or you found one?

**Comment by sujon2100** [comment]
> Hi,
> 
> May I know if you are still looking for a team mate or you found one?

Now I am looking for only presentation/essay/Covid19. How about you?

**Comment by sujon2100** [comment]
> Hi,
> 
> May I know if you are still looking for a team mate or you found one?

By the way, someone has contacted me but now out of the communication. If I don't get any response, I will let you know soon.

**Comment by sashikanthr** [comment]
> By the way, someone has contacted me but now out of the communication. If I don't get any response, I will let you know soon.

I can join for presentation/essay/Covid19. Let me know if you dont get any response. Thank you.

**Comment by sujon2100** [comment]
> > By the way, someone has contacted me but now out of the communication. If I don't get any response, I will let you know soon.
> 
> I can join for presentation/essay/Covid19. Let me know if you dont get any response. Thank you.

I found a teammate. But Nick can help you, just contact nsteele@kth.se.

**Comment by sashikanthr** [comment]
> I found a teammate. But Nick can help you, just contact [nsteele@kth.se](mailto:nsteele@kth.se).

Thank you. I will contact him.

**Comment by gluckzhang** [comment]
Hi @sujon2100 , I am organizing the open issues. If you have found team members, please consider closing the issue. Thanks :)
