### ISSUE TITLE
Results & Feedback 2020

### ISSUE THREAD

**Issue by monperrus** [KTH/devops-course#423]
Here we post the results & grades.

**Comment by monperrus** [comment]
Presentations of week2:

DISTINCTION: Traditional unit testing vs. Property-based testing, what are the differences? by Gunnar Applelid and Kasper Liu
* yes: timing, relevance, motivation, technical, reflective, take-home, loudly, humor, illustration, readable-slides
* remarkable: technical(code snippets explained), well-structured(thesis-antithesis-synthesis), engagement(poll) 

DISTINCTION: Health of git repositories: the "bus factor" by Victor Josephson and Maël Madon
* yes: relevance, well-structured, motivation, technical, reflective, take-home, loudly, illustration
* remarkable: originality, relevance(open-source software supply chain), technical(ran code), engagement(applied to course repo)

PASS: Docker: Security features by Sigrún Sigurdardottir and Javier Ron Arteaga
* yes: timing, relevance, motivation, technical, reflective, take-home, take-home, illustration, readable-slides
* remarkable: relevance(containerization)

Congrats Gunnar, Kasper, Victor, Maël, Sigrún, Javier!

**Comment by monperrus** [comment]
Presentations of week 3
========================

Thank you very much for the 7 presentations of today. They were all very relevant to DevOps while exploring the topic from vastly different perspectives. Overall, the balance between the two speakers in each presentation was perfect.

Distinction
-----------

[Code coverage](/contributions/presentation/week3/almajni-felixlut) by Nour Alhuda Almajni and Felix Luthman 👍 👍 

yes: well-structured, motivation, originality, take-home, loudly, readable-slides

remarkable: illustration, technical(advanced coverage criteria) such as parameter value coverage), reflection


Pass
----

[Can docker replace VMware?](/contributions/presentation/week3/htchan-lhlchoy) by Ho Ting Chan and Louise Hui Ling Choy 👍 

yes: relevance, well-structured, illustration(clear explanation docker vmware), readable-slides, motivation, technical, originality, loudly 


[Travis vs Jenkins, a comparison of two popular CI tools](/contributions/presentation/week3/jonasjo5-marcusew) by Jonas Johansson and Marcus Jonsson Ewerbring 👍 

yes: relevance, timing, humour (Ant joke + noobs), reflection, take-home, loudly, readable-slides, well-structured

comment : we appreciate the setup with 2 microphones and the mention of notable plugin Blue Ocean 🔵

[ATDD vs TDD](/contributions/presentation/week3/uggelberg-west) by Balthazar West and Richard Uggelberg 👍

yes: relevance, originality, well-structured, motivation, readable-slide, take-home, timing, loudly 

remarkable: reflection (venn diagram very relevant)


Repeat
----

The following presentations did not reach seven satisfied grading criteria. Per the rule specified in the [course homepage](https://github.com/KTH/devops-course#rules), the groups are given the opportunity to repeat the presentation in May 2020. 

[Automation Testing](/contributions/presentation/week3/mrhasa-mjza) by MD Rezaul Hasan and Muhammad Jahangir Zafar

yes: relevance, loudly

guidelines for repetition in May:
* strict timing
* slides should contain little text and be focused
* the presentation shall contain deep technical content
* the concepts should be presented on different slides than the implementation technologies

comments: 1) all students in a presentation must be present and speak in a balanced manner 2) typos are not accepted, the usage of spell checkers is recommended.  

[Monolithic vs. Microservice architectures](/contributions/presentation/week3/sevinc-rezkalla) by George Rezkalla and Diego Leon

yes: relevance, readable-slides, timing, loudly  

guidelines for repetition in May:
* avoid bullet lists with shallow points and statements
* the presentation shall contain deep technical content
* the take-home shall be grounded on facts

comments: 1) it's excellent to have slide numbers, thank you 2) avoid slides with only logos

[An Introduction to Application-level Chaos Engineering and Its Tools](/contributions/presentation/week3/vemula-akhily) by Nagasudeep Vemula and Akhil Yerrapragada

yes: relevance, loudly, originality

guidelines for repetition in May:
* strict timing, don't spend 2:51 min on the title slide
* slides should contain little text and be focused
* do not mix a demo and a presentation
* the presentation shall contain deep technical content

Best regards,

--Benoit Baudry, Martin Monperrus

**Comment by bbaudry** [comment]
[Presentations of week 4](https://github.com/KTH/devops-course/tree/master/contributions/presentation/week4)
========================

Thank you very much for the 7 presentations of today. They were all very relevant to DevOps, the speakers had prepared very well timed presentations and the speakers had very good setups for online presentations.

Distinction
----------- 

[How to Build A DevOps Culture](/contributions/presentation/week4/jii-stinalan) by Johanna Iivanainen and Stina Långström 👍 👍

yes: readable-slides, illustration, relevance, timing, take-home

remarkable: engagement (with a poll and contrast between perspectives), technical (strong, real-life example, well documented and integrated), originality

[Devops and Security - DevSecOps, What Is It? Why Do You Need It?](/contributions/presentation/week4/ppmo-eyrun) by Eyrún Þrastardóttir and Paul-Philip Mousulet 👍 👍

yes: humour (slide 4 is really nice!), well-structured, originality, timing

remarkable: technical, loudly, motivation

Pass
----

[DevOps in an Industry Implementation](/contributions/presentation/week4/hiteshs) by Hitesh Sharma 👍

yes: timing, readable-slides, engagement (underline on the slides), relevance, take-home, technical, relevance

[Configuration Management with Ansible](/contributions/presentation/week4/jadlers-dingli) by Jacob Adlers and Dingli Mao 👍

yes: timely, relevance, well-structured, motivation, loudly, originality, readable-slides, reflection (comparison with other similar tools)

remarkable: technical (many concrete examples)

[Monitoring in DevOps](/contributions/presentation/week4/paulher-hmellin) by Paul Löwenström and Henrik Mellin 👍

yes: relevance, motivation, loudly, illustration, humour, readable-slides, timing

[A/B Testing](/contributions/presentation/week4/rosquis-shapour) by Christine Rosquist and Shapour Jahanshahi 👍

yes: relevance, motivation, engagement (through the chat), loudly, timing, originality

remarkable: readable-slides, illustration

[Test Amplification in DevOps](/contributions/presentation/week4/xmas92-Callet91-Volminger) by Alexander Volminger, Axel Boldt-Christmas and Carl Jensen 👍

yes: relevance, technical (code examples and precise descriptions), illustration, readable-slides, timing, well-structured, loudly, reflection

Best regards,

-- Benoit Baudry

**Comment by monperrus** [comment]
Presentations of week 5
====================== 

Distinction
-----------

**A Comparison between Blue/Green deployment and Canary deployment by David Johansson and Johan von Hacht**👍👍

* yes: motivation, relevance, loudly, originality, well-structured, take-home, timing
* remarkable: technical, reflection, readable-slides
* comment: one link at the end to go further is an excellent practice

**Securing Kubernetes Cluster with Network Policies by Emelie Tham and Philip Wester**👍👍

* yes:  loudly, originality,  relevance, timing, well-structured
* remarkable: motivation, technical, readable-slides


Pass
-----

**Git Hooks: What They Are and How to Use Them by Albert Asratyan and Vincent Lohse**👍

* yes: motivation, relevance, loudly, well-structured, technical, readable-slides 
* remarkable: originality
* advice: never start a demo when you're low on time

**Canary Releases by Sashikanth Raavikanti and Nicholas Steele**👍

* yes: relevance, timing, well-structured, readable-slides, originality, loudly
* remarkable: technical (illustration with the Netflix technology, discussed a research paper)

**Agile Software Development by Tommy Samuelsson and Louise Zetterlund**👍

* yes: humor, engagement, loudly, timing, illustration, reflection (very good answers to questions), readable-slides
* comment: Agile software development was hot in years 2000, but today is almost a vintage topic. Also, in this course, we expect technical work, make sure to meet this criterion in the other tasks


Repetition
----

**DevOps Teams - Roles,Responsibilities and Habits by Christina Sunnegårdh and Klara Eserstam**

* yes: illustration, loudly, originality (for the interview with 2 developers), timing
* suggestions for repetition:
  * motivation: why is this presentation and topic important?
  * technical: presentation was technically shallow: talk scientifically about the interview methodology and content
  * take-home: too shallow

Best regards,

--Benoit Baudry and Martin Monperrus

**Comment by monperrus** [comment]
Presentations of week 6
==

Distinction
-----------


**Code Review in DevOps by Ruwaid Louis and David Stevens** 👍👍

* remarkable: originality,  reflection  (code review can be automated, you relate code review, linters and onboarding), readable-slides (high graphical quality)

* yes: relevance, motivation, loudly, engagement, well-structured, timing, illustration (inverse pyramid)


Pass
-------

**Security in Docker Container by Aristotelis Kotsias and Georgios Tagkoulis** 👍


* remarkable: technical, reflection

* yes: engagement (online polls), originality (for the rare mention to seccomp), readable-slides,  timing,  take-home, relevance, motivation, loudly

**Docker and Its Use in DevOps by Joar Rutqvist and Pontus Broberg** 👍

* remarkable: well-structured (very pedagogical)

* yes: loudly, readable-slides, technical illustration, timing, relevance, engagement (questions at the beginning)


**Tracing by Johan Vikström and Sandro Lockwall Rhodin** 👍

* yes: originality, illustration, motivation, technical (flame graph, dapper, jaeger), take-home, timing, relevance

* comment: congratulations for the strong sources to build your presentation; note it's good to speak slowly to improve the clarity of your message.



Repetition
----------

To register a repetition slot, see https://github.com/KTH/devops-course/blob/master/contributions/repetition-planning.md

**Novel Decentralized Discussion Tool by Gustav Dowling**

* yes: loudly, readable-slides, timing 

Guidelines for repetition. Here are some suggestions in order to pass on other criteria for your presentation:

* well-structured: introduce a concept related to DevOps (not a specific tool), then organize the presentation to go from a general definition of the concept down towards one specific, interesting and technical part of the concept.
* motivation: once you have selected and clearly defined one concept, explain in one slide the challenging DevOps problem that is solved or discussed in the presentation.
* relevance: this criterion is tightly related to the motivation and consists in arguing the importance of your concept for DevOps and for the DevOps course at KTH.
* technical: explain one deep technical part of the concept (for example, detail one hard example, explain one core algorithm, go through the inner workings of a data structure, etc.).
* originality: the concept you choose to present must be timely and should not have been presented elsewhere in the course or on the web.
* reflection: provide your opinion about the value and importance of the concept you present, compare it with the related work.
* take-home: based on your reflection about the concept and given the importance of this concept, what is the key pedagogical outcome for your peers who follow the DevOps course.
* illustration: when appropriate, use nice figures, code snippets, clear diagrams to illustrate the key parts of the concept that your present.


**Chaos Engineering + Chaos Monkey by Per Fahlander and Johan Settlin**


* yes: motivation, relevance, timing, well-structured, loudly

Guidelines for repetition. Here are some suggestions in order to pass on other criteria for your presentation:
* main comment: a presentation is not a tutorial, it is a piece of reflection on a given topic, raise the level of abstraction, do not show commands
* technical: what are the failures that a chaos monkey simulates?
* originality: ChaosMonkey is the oldest and most known chaos engineering tool: what would be other notable ones?
* take-home: qualify the take-home message, write a least one full fledged sentence in more than 4 words
* illustration: figures are not only for recreation, they have a pedagogical value. Example of potential figures: what is a chaos engineering workflow in a company? what is the relation between "steady state", "hypothesis" and "noise"?
* readable-slides (too much text), be careful of typos (eg "it's first prototype")


**An Overview of Serverless Computing by Pojan Shahrivar and Akshay Sinha**

* yes: originality, relevance, loudly,  timing, engagement (poll)

Guidelines for repetition. Here are some suggestions in order to pass on other criteria for your presentation:
* main comment/structure: a presentation is not a tutorial, it is a piece of reflection on a given topic, raise the level of absraction, do not show commands and irrelevant listings
* technical: what is the key algorithm / design choice that makes sereverless computing unique and interesting? Describe and discuss one or two such technical points.
* take-home: a take-home message is not a piece of advertisement for a commercial product
* illustration: figures and listing shall serve to reflect about the technicalities of serverless computing, not to give guidelines about how to install or use a specific tool.
* readable-slides: do not alternate black fonts over white background and vice versa
* motivation: explain in one slide the DevOps problem that is solved, in a slide 2 starting with "Why?"

Best regards,

--Benoit Baudry and Martin Monperrus

**Comment by gluckzhang** [comment]
# Result of The Fuzzing Competition

Thanks to all the participants for putting effort into this challenge! Here is a short summary about the competition.

## How many files and lines of code are included in the coverage calculation?
Files: 2403  
Total lines of code: 352486

## How do we evaluate the submissions?
We implemented a script to automatically execute the commands listed in the `input.txt` file in a top-down order until the 1-hour execution budget is used up. The coverage score is calculated with the help of [DynamoRIO](https://github.com/DynamoRIO/dynamorio).

## Competition Results
| Group Members | Coverage | Exe. Time | Result |
| ------------- | -------- | -------------- | ---- |
| Axel Boldt-Christmas | 48.0% | 1h | Distinction |
| Tommy Samuelsson and Stina Långström | 30.4% | 1h | Distinction |
| Javier Ron Arteaga and Muhammad Jahangir Zafar | 18.8% | 1h | Pass |
| Gustav Dowling and Keivan Matinzadeh | 16.5% | 1h | Pass |
| Adam Björnberg | 10.7% | 1h | Pass |
| Christer Winge | 9.3% | 621s | Pass |
| Ho Ting Chan and Louise Hui Ling Choy | 3.3% | 27s | Repetition |

Concrete feedback for groups who need to repeat has been sent via emails. For repetition in this task, you will send an email to `dd2482@eecs.kth.se` with the updated solution before the end of May.

**Comment by monperrus** [comment]
Superseded by https://github.com/KTH/devops-course/issues/921
