### ISSUE TITLE
Looking for a teammate for demo and essay

### ISSUE THREAD

**Issue by nour95** [KTH/devops-course#427]
Hi 
I am searching for a partner for demo and essay.
Email: almajni@kth.se

**Comment by gluckzhang** [comment]
Hi @nour95 , have you found your teammate? If so please consider closing the issue. Otherwise you could also take a look at all the issues with label [`collaboration_wanted`](https://github.com/KTH/devops-course/labels/collaboration_wanted).

**Comment by nour95** [comment]
Hi! I didn't find a teammate yet. But thank you, I will check them now. And If I find one, I will close this issue. 
Thanks again
