### ISSUE TITLE
Choosing the same topic

### ISSUE THREAD

**Issue by georgewbar** [KTH/devops-course#437]
Hi,
I have a question regarding topics. My teammate @sujon2100 and I decided to do a tutorial on Microsoft Azure. However, when doing our PR, we went through old PRs to see the template for some PRs. By chance, we found a PR that have very similar to ours. The PR #379 was about a tutorial of CI/CD pipeline in Microsoft Azure. We did not create our PR yet.

Is it allowed that two teams do tutorials on nearly the same topics or not?

**Comment by gluckzhang** [comment]
Hi @georgewbar , it's fine for different teams to work on a similar topic. We believe that every team has their own insights into the topic. Plus in all cases and task categories, plagiarism is strictly forbidden, per the KTH rules which are very strict.

**Comment by georgewbar** [comment]
@gluckzhang, Thanks for the answer!

**Comment by gluckzhang** [comment]
The question has been answered. So I'm closing the issue now :)
