### ISSUE TITLE
Is it okay to create your own bot as an open-source?

### ISSUE THREAD

**Issue by johannaii** [KTH/devops-course#447]
Me and @louisezetterlund are trying to find something to do for the open-source task. We both think it would be fun to create our own bot (for Discord, Github or similar). We have tried to find issues to work with, but have not find yet any that matches our competence, interest, the criteria for the task or are related to DevOps. Would creating a bot be enough for the open-source task?

**Comment by gluckzhang** [comment]
Hi @johannaii , it's OK to create your own project as an open-source task. We will discuss more about the qualification when you create a PR to show your idea :)

**Comment by gluckzhang** [comment]
The question has been answered. Issue closed.
