### ISSUE TITLE
Tools for videos (presentations / screencast / tutorial) 

### ISSUE THREAD

**Issue by monperrus** [KTH/devops-course#463]
In this thread, we share tools that can help us to make great videos for youtube/podcast presentations, screencasts, tutorials.

**Comment by monperrus** [comment]
Video Puppet makes it easy to script videos using plain text (Markdown) files.: https://videopuppet.com/docs/script/

**Comment by monperrus** [comment]
Collection of scripts I use to automate various aspects of podcast production for The Command Line Podcast. 
https://github.com/cmdln/autocast
https://thecommandline.net/category/podcast/

**Comment by gluckzhang** [comment]
asciinema: https://github.com/asciinema/asciinema/
asciinema lets you easily record terminal sessions and replay them in a terminal as well as in a web browser.

**Comment by bbaudry** [comment]
Thank you @christinasunnegardh  for sharing the link to the Adobe tools
https://intra.kth.se/it/programvara-o-system/programvara/installera/download/acrobat/adobe-for-students

**Comment by annsudo** [comment]
OBS (https://obsproject.com/ ) for screen recording and streaming.  Elegant and free  🙌
