### ISSUE TITLE
When is the presentation repetition in may?

### ISSUE THREAD

**Issue by georgewbar** [KTH/devops-course#481]
* We got feedback that we need to do presentation again in may. When will it be? #423 "Microservices vs Monolithic"
* Is it possible to discuss the criteria for passing in the lab session for example?

**Comment by gluckzhang** [comment]
Hi @georgewbar , if I remember correctly, last year this was arranged based on the team and the examiner's calendar. This year should be the same. I will let you know when I get more details.

**Comment by georgewbar** [comment]
Ok. We need to get more detailed feedback and discussion than the comments on the grading issue. is it possible to discuss the criteria for passing in the lab session for example?

**Comment by gluckzhang** [comment]
@georgewbar , yes, you could discuss this with our TAs during a lab session.

**Comment by gluckzhang** [comment]
I will close this issue for now. @georgewbar you could contact us again if you have further questions :)
