### ISSUE TITLE
Official COVID-19 hackathon in Sweden

### ISSUE THREAD

**Issue by gluckzhang** [KTH/devops-course#486]
Hi all,

I just found this by accident. Maybe some of you will feel interested.

Official COVID-19 hackathon in Sweden (April 3 - 6, online)
An initiative by The Swedish Government
https://www.hackthecrisis.se/

@monperrus @bbaudry @SophieHYe @cesarsotovalero , is it good to connect this activity with our `covid-19` task category? For example, students who register a task in `covid-19` are also encouraged to submit their ideas to the hackathon.

**Comment by monperrus** [comment]
> students who register a task in covid-19 are also encouraged to submit their ideas to the hackathon.

Yes, that's a good idea!

**Comment by gluckzhang** [comment]
This issue is closed since the hackathon has ended.
