### ISSUE TITLE
Looking for Teammate: Tutorial

### ISSUE THREAD

**Issue by pojans** [KTH/devops-course#525]
Hi,

Looking for a teammate to do the tutorial with.
I'd love to explore CI/CD for tutorial.

**Comment by hittesharma** [comment]
Have you got partner for essay?

**Comment by richarduggelberg** [comment]
Hi, I have considered the exact same thing. 

Are you still looking for a teammate for the tutorial?

//Richard

**Comment by pojans** [comment]
> Hi, I have considered the exact same thing.
> 
> Are you still looking for a teammate for the tutorial?
> 
> //Richard

Send me an email to pojans@kth.se and we'll take it from there.

/ P
