### ISSUE TITLE
Problems with creating a deliver stage in Jenkins for React app

### ISSUE THREAD

**Issue by johannaii** [KTH/devops-course#528]
Me and @Zodbigt are trying to create a Jenkins' pipeline for our covid19 project, but we are having problems with creating a Deliver stage. Right now we have a Build stage and a Deliver stage in our pipeline, but the Deliver stage raises some error that we don't know how to fix and probably it is because of them we cannot access the app in the browser.  

![error_jenkins](https://user-images.githubusercontent.com/45517649/78799867-03ee1000-79bb-11ea-9a2c-fafc2ade7a00.png)

This is the first time we are creating a Jenkins pipeline so none of us have so much experience of it. I have tried to google it, but have not find anything that helps. Is there anyone who has a lot of knowledge of creating Jenkins' pipelines for React/Nodejs apps that might now how we should fix it? :)

**Comment by monperrus** [comment]
I assume this can be closed now. Thanks!
