### ISSUE TITLE
Question regarding the presentation

### ISSUE THREAD

**Issue by georgewbar** [KTH/devops-course#531]
Hi,
@dieflo4711 and I are going to repeat the presentation in May. We would like to ask if it is allowed to change the topic of the new presentation to not be the same as the old presentation or must it be the same topic as the old presentation?

**Comment by gluckzhang** [comment]
Hi @georgewbar , @dieflo4711 , in this case you need to redo the presentation with the same topic.

**Comment by georgewbar** [comment]
@gluckzhang thanks for the answer. A follow up question: our presentation was about "Microservices vs Monolithic architectures". We are thinking about focusing very little about monolithic architectures and focusing a lot on microservices architectures from the technical view. 

For example, we thought about choosing three of design patterns for microservices explained in [https://docs.microsoft.com/en-us/azure/architecture/microservices/design/patterns](https://docs.microsoft.com/en-us/azure/architecture/microservices/design/patterns), and discussing and reflecting about them in more detail. So, it will be less talking about benefits and disadvantages regarding microservices vs monolithic, and it will be more talking about comparisons between different design patterns.

Therefore, we thought about maybe getting rid of monolithic architectures nearly totally if the presentation time is not enough, to have more technical details about microservices. Does this count as changing the topic. We are trying to focus on the technical parts as advised by the recommendations we got in the feedback to our old presentation.

**Comment by georgewbar** [comment]
@gluckzhang what do you think about the above question?

**Comment by gluckzhang** [comment]
Hi @georgewbar , I will double-check with the teaching team and get back to you asap :)

**Comment by gluckzhang** [comment]
Hi @georgewbar , this does not count as changing the topic. Feel free to add further questions here. Otherwise you could close the issue, thanks :)

**Comment by georgewbar** [comment]
Thanks for the answer!
