### ISSUE TITLE
Feedback Request: Tutorial for Azure DevOps Pipeline (Agile from start to end) for commit (#379) 

### ISSUE THREAD

**Issue by hittesharma** [KTH/devops-course#559]
Hi @SophieHYe ,

Please find the pdf of the tutorial attached, we are aiming for distinction criteria.
Feedback Request: Tutorial for Azure DevOps Pipeline (Agile from start to end)
Commit ID (#379) 

Third team member (eyueltb) could not contribute much due to some unavoidable circumstances.

[Azure DevOps Pipeline and More.pdf](https://github.com/KTH/devops-course/files/4474943/Azure.DevOps.Pipeline.and.More.pdf)

**Comment by gluckzhang** [comment]
Hi @hittesharma , in order to register a feedback request, please follow the instructions [here](https://github.com/KTH/devops-course/blob/master/contributions/feedback-planning.md) to propose a PR instead of an issue. Thanks.

**Comment by gluckzhang** [comment]
Issue closed. The PR (#588) has been merged.
