### ISSUE TITLE
Missing deadline

### ISSUE THREAD

**Issue by georgewbar** [KTH/devops-course#578]
Does one fail the whole course if one misses the deadline at the end of april?

**Comment by gluckzhang** [comment]
Hi @georgewbar , if one misses a task deadline at the end of april, that task will be marked as a failure. But there will be one opportunity in may for repeating the failed task. A repeated task cannot be passed with distinction. A task can only be repeated once.

**Comment by georgewbar** [comment]
Thanks for the answer!

**Comment by gluckzhang** [comment]
Based on the Q&A session in today's lecture, we should also clarify this in the `README`: students cannot repeat a task if he only registers it before the deadline but does not submit anything.
