### ISSUE TITLE
Alternative to KTH Box

### ISSUE THREAD

**Issue by xmas92** [KTH/devops-course#581]
Hi I just checked out KTH Box but it seems to only be available for KTH employees. 
Do you have an alternative that you prefer we use or can we use any cloud storage provider?
Is there any good alternative you know and can recommend?

**Comment by gluckzhang** [comment]
Hi @xmas92 , if you mean a submission for fuzzing-competition, you could use any cloud provider as you prefer :)

**Comment by xmas92** [comment]
Alright I will find some free provider then.
