### ISSUE TITLE
[competition question] What happens if my input hangs FFMPEG?

### ISSUE THREAD

**Issue by GustavDowling** [KTH/devops-course#597]
For example, if I find a bug where I send ffmpeg into an infinite loop, will the competition device running it notice this and go to the next input eventually?

Or if i'm trying to overwrite and existing file and it asks for confirmation, etc etc

**Comment by gluckzhang** [comment]
Hi @GustavDowling 

> For example, if I find a bug where I send ffmpeg into an infinite loop, will the competition device running it notice this and go to the next input eventually?

We will add a timeout for each line of arguments. I haven't decided on the exact value yet. Maybe 30s if it is enough.

> Or if i'm trying to overwrite and existing file and it asks for confirmation, etc etc

Good question. All the commands will be executed automatically. Thus there should be none interaction. I would recommend to add a `-y` option to such commands. Or use a unique file name. Or redirect the output to `/dev/null` if it is not used by other commands.

**Comment by gluckzhang** [comment]
Closed for now.
