### ISSUE TITLE
DevOps vs SRE

### ISSUE THREAD

**Issue by veggiemonk** [KTH/devops-course#630]
I was asked during the presentation what is the difference between DevOps and SRE.

I feel my answer was incomplete and maybe wrong so here is a short video that explains it better than I can 

https://youtu.be/uTEL8Ff1Zvk

**Comment by gluckzhang** [comment]
Thanks @veggiemonk for giving the talk and also this pointer. Have a nice day!

**Comment by SiAslett-Round** [comment]
Yes, that is a great video. I think i saw that one as part of an SRE course on Coursera i was doing. Fundamentally, I'd say they were two sides of the same coin. A lot of the SRE stuff underpins good/great practice for the Ops side as well as feeds into the Dev side. I also really liked the whole SLO/SLI as apposed to SLA etc, I still refer to those today.

**Comment by hittesharma** [comment]
Yes, I asked this question. I had seen that video earlier, I just enabled the discussion after the presentation. :)
