### ISSUE TITLE
Wrong directory name

### ISSUE THREAD

**Issue by balwes** [KTH/devops-course#671]
I did a presentation in week 3 ([link](https://github.com/KTH/devops-course/tree/master/contributions/presentation/week3/uggelberg-west)) but the directory is not named according to the convention. The name should be "uggelberg-bwest", is this a problem?

**Comment by gluckzhang** [comment]
Hi @balwes , please create a PR to fix the folder name. Our script automatically counts the number of registered tasks based on these folder names. You will have incorrect statistics if the folder name is wrong :)
