### ISSUE TITLE
Covid19 Deadline?

### ISSUE THREAD

**Issue by zen93** [KTH/devops-course#674]
Hi,
According to the rules page (https://github.com/KTH/devops-course#rules), it is not clear when the deadline for the covid19 task is? Can you please clarify?

**Comment by gluckzhang** [comment]
Hi @zen93, thanks for pointing this out. Covid19 has the same deadline with the other categories like tutorial and essay. I will fix this in the `README.md`.

**Comment by gluckzhang** [comment]
The deadline has been clarified in commit [`a7ae280`](https://github.com/KTH/devops-course/commit/a7ae2802f1918cda622a37cf0be46695036f45b2). Issue closed.
