### ISSUE TITLE
Presentations: 7 accepted PRs 6 timeslots? Also advice wanted.

### ISSUE THREAD

**Issue by GustavDowling** [KTH/devops-course#683]
Here it says no more than 6 will be arranged for any week: https://github.com/KTH/devops-course/tree/master/contributions/presentation

However, looking in the week6 folder there are 7 people with accepted PRs, will time be made for everyone?

Also, my presentation is in the form of a video (but i'll be there to take questions and such ofcourse), I wonder if relaxing ambient background music is allowed? In my opinion it makes the video a lot easier to watch and better.

**Comment by gluckzhang** [comment]
Hi @GustavDowling , thanks for mentionting this. This was discussed during last lecture and we finally arranged 7 slots for week 6. So every registered topic has secured its time slot.

Regarding your presentation, I would like to suggest doing it lively. It's common to do some rehearsals before a presentation. But usually, such a task would expect students to lively introduce the topic and answer questions. What do you think?

**Comment by GustavDowling** [comment]
Right now I have a video, although I could ofcourse say the same things live. I just think it's difficult to present when you are just talking into a microphone with no eye contact, so I decided to pre record a video presentation so that I can cut out awkward silence and similar. I'll still be there to answer any questions about my topic ofcourse.

This is fine right?

**Comment by gluckzhang** [comment]
Hi @GustavDowling , sorry, I have double-checked with the teaching team and this is not allowed. Student will give a presentation lively. We will optimize the instructions later.
