### ISSUE TITLE
Presentation Assessment

### ISSUE THREAD

**Issue by hittesharma** [KTH/devops-course#711]
My presentation was in week 4 but I could not see any assessment done in my presentation directory (https://github.com/KTH/devops-course/tree/master/contributions/presentation/week4/hiteshs). Do I need to wait more or look somewhere else?

**Comment by cwinge** [comment]
@hittesharma  Assessment is available for week 4 in the following link:
https://github.com/KTH/devops-course/issues/423#issuecomment-610421436

**Comment by bbaudry** [comment]
> @hittesharma Assessment is available for week 4 in the following link:
> [#423 (comment)](https://github.com/KTH/devops-course/issues/423#issuecomment-610421436)

Thanks @cwinge for the redirection

**Comment by gluckzhang** [comment]
The question has been answered. Issue closed :)
