### ISSUE TITLE
Fuzzing

### ISSUE THREAD

**Issue by monperrus** [KTH/devops-course#78]
References:

* https://en.wikipedia.org/wiki/Fuzzing
* https://www.fuzzingbook.org/

**Comment by monperrus** [comment]
Google OSS-fuzz
https://opensource.google.com/projects/oss-fuzz
https://github.com/google/oss-fuzz

**Comment by monperrus** [comment]
CodeAlchemist: Semantics-Aware Code Generation to Find Vulnerabilities in JavaScript Engines
https://daramg.gift/paper/han-ndss2019.pdf

**Comment by bbaudry** [comment]
fuzzing for JavaScript engines
https://saelo.github.io/presentations/offensivecon_19_fuzzilli.pdf

**Comment by monperrus** [comment]
> "Whitebox fuzzing has found one-third of all file fuzzing bugs during the development of Windows 7, saving millions of dollars in potential security vulnerabilities. The technique is in use today across multiple products at Microsoft."

Billions and Billions of Constraints: Whitebox Fuzz Testing in Production
https://patricegodefroid.github.io/public_psfiles/icse2013.pdf

**Comment by monperrus** [comment]
AFL won the competition! AFL is a greybox fuzzer.

More on greybox fuzzing: https://www.fuzzingbook.org/html/GreyboxFuzzer.html

**Comment by monperrus** [comment]
EnFuzz: Ensemble Fuzzing with Seed Synchronization among Diverse Fuzzers
_"we implement EnFuzz , a prototype basing on four strong open-source fuzzers (AFL, AFLFast, AFLGo, FairFuzz)"_
https://arxiv.org/abs/1807.00182

**Comment by bbaudry** [comment]
The LAVA Synthetic Bug Corpora 
https://moyix.blogspot.com/2016/10/the-lava-synthetic-bug-corpora.html
