### ISSUE TITLE
Question about easter egg in demo

### ISSUE THREAD

**Issue by louisezetterlund** [KTH/devops-course#790]
Hi,

I think the criterion about the easter egg in the demo is a bit confusing. What classifies as an easter egg? Does it have to be in the screencast? Can we show what the easter egg is or does the user have to find it themselves? Could it be interactive (like when the user clicks on a link) or should it just be something in the background in the screencast?

**Comment by cwinge** [comment]
I was having similar thoughts about that criteria. It does say "The demonstration screencast contains an easter egg", so I would assume that is has to be in the actual screencast. Which in my opinion can be a bit boring, at least if it is part of the demo that others can test themselves. 

What I did to "solve" my problems with it, was to simply make two screencasts. One with only hints towards the actual easter egg and one that clearly shows the included easter egg. This obviously doesn't answer your question, but might be an option.

**Comment by gluckzhang** [comment]
Hi @louisezetterlund , sorry for the late reply. An easter egg is meant to be hidden and/or fun. So you should not explicitly mention the easter egg in your screencast (e.g., in the subtitle). If you think readers may not notice the easter egg, you could mention it in the video description or the readme file that you submit.
