### ISSUE TITLE
Any other courses to continue learning in this path

### ISSUE THREAD

**Issue by sashikanthr** [KTH/devops-course#812]
Hi,

I am interested in the Software Technology track and I particularly liked this course. I am planning to take some other courses that follow the path. I am taking Large Scale Software Development next semester and I can take 3 more courses of my choice. Could you suggest what other courses can I go for?

**Comment by monperrus** [comment]
Very good question, we recommend all the software courses in the "MSc Software Engineering of Distributed Systems" and in the "MSc Computer Science" 

* See section "Software track" of https://www.kth.se/en/studies/master/software-engineering-distributed-systems/course-overview-1.268670

* See section "Software technology track" of https://www.kth.se/en/studies/master/computer-science/course-overview-1.502267
