### ISSUE TITLE
Complete demo after 5th of May?

### ISSUE THREAD

**Issue by jrutqvist** [KTH/devops-course#816]
I asked this in the lecture earlier but was not completely clear on what the answer meant so I thought I should get clarification,

I was not able to get my demo to work for the demo presentations today, is it still possible to pass the demo assignment if I submit my demo before the hard deadline?

When I asked it was mentioned that the final deadline was may 9th, but I was not sure if it was in response to my question, and since it says "must be ready by 09:00 05/05" in the instructions I thought I should double check. I completely understand if the deadline is blown and I cannot complete the assignment, just want to know for sure!

**Comment by gluckzhang** [comment]
Hi @jrutqvist , thanks for confirming this with us. I think Martin means the final deadline for groups who have submitted their demos is May 10th. The rule is clear in the `README`: the demo must be ready for May 5 2020, 9h00 Stockholm time. Thus it's impossible to pass the demo assignment if one missed the deadline.

Thanks for your understanding!
