### ISSUE TITLE
Missed Demo day

### ISSUE THREAD

**Issue by dieflo4711** [KTH/devops-course#827]
Hi,

Unfortunately, I couldn't attend the online demo day. However, my teammate attended and gave feedback and we received feedback from more than 3 people. Could I instead give feedback now?

Regards, Diego​

**Comment by gluckzhang** [comment]
Hi @dieflo4711 , thanks for pointing out the issue. Please give feedback to 3 demos as soon as possible. It's still helpful for teams to enhance their final submission :)
