### ISSUE TITLE
Deadline for essay submission

### ISSUE THREAD

**Issue by HarisAdzemovic** [KTH/devops-course#84]
Hi,
With risk of asking another of my patented "stupid questions", I've been unable to find the deadline for the essay submission. Does anyone know?
Thanks!

**Comment by gluckzhang** [comment]
Hi @HarisAdzemovic , it's a good question actually, we should have clarified the deadlines :)
I'll confirm with Martin and Benoit, and be back to you asap.

**Comment by gluckzhang** [comment]
Hi @HarisAdzemovic , all,
Just got confirmation from Martin, the deadline for essay submission is **April 30th 23:59**. I also clarify all deadlines here: https://github.com/KTH/devops-course/blob/master/announcement/README.md

Thanks and have a nice day!

**Comment by HarisAdzemovic** [comment]
Thank you for the quick answer!
Have a nice day yourself! :)
