### ISSUE TITLE
Searching group partner for Demo 

### ISSUE THREAD

**Issue by Parumita** [KTH/devops-course#85]
Hello ,

I am searching group partner for Demo . If anyone is interested please contact with me . 
Mail address : parumita@kth.se 

Thank You .

**Comment by SophieHYe** [comment]
Hi Parumita,

Would you also interested in doing an essay? Yipei is looking for a partner for an essay in  #92, maybe you two can have a discussion :) Good luck!

**Comment by gluckzhang** [comment]
FYI, Anastasia is also looking for partners, you could contact her by email: anapro@kth.se

**Comment by gluckzhang** [comment]
The issue has been resolved. I will close it.
