### ISSUE TITLE
Personalized feedback break-out sessions on Zoom, May 12 2020

### ISSUE THREAD

**Issue by monperrus** [KTH/devops-course#858]
If you want to have a personalized feedback break-out Zoom sessions with the profs or TAs, post here your KTH login and the task you'd like to discuss.

**Comment by nagavem** [comment]
Hello,

KTH Logins: vemula@kth.se    mjza@kth.se     chikafa@kth.se

We would like to have a personalized feedback discussion for our demo : https://github.com/KTH/devops-course/tree/master/contributions/demo/mjza-chikafa-vemula

**Comment by Marcus9512** [comment]
Hello,

I would like some personalized feedback on my essay if it´s not too late : )

KTH Login: marcusew@kth.se

Link to essay: https://github.com/KTH/devops-course/tree/master/contributions/essay/marcusew

**Comment by cesarsotovalero** [comment]
Hi @nagavem , please enter now for the personalized feedback session https://kth-se.zoom.us/j/63485266213

**Comment by Paul-Philip** [comment]
Hi,

If you got time over, I'm interested in feedback on the  topic of my essay itself not really the structure or so, perhaps more of a discussion rather than feedback. I'm looking into the area for a potential thesis.

https://github.com/KTH/devops-course/tree/master/contributions/essay/ppmo

**Comment by javierron** [comment]
Hello, @s1grun and I would like personalized feedback on our open-source task

**Comment by SophieHYe** [comment]
Hi @Paul-Philip, could you please come to this zoom meeting and then we can discuss :)

**Comment by bbaudry** [comment]
@javierron , we have opened a zoom, id: 68572908847

**Comment by cesarsotovalero** [comment]
Hi @Marcus9512, please enter to this zoom meeting for the personalize feedback session https://kth-se.zoom.us/j/62401806754

**Comment by akhilyerrapragadaa** [comment]
Hi,

KTH Login: akhily@kth.se

I would like to have personalized feedback on demo:
https://github.com/KTH/devops-course/tree/master/contributions/demo/akhily

**Comment by monperrus** [comment]
@akhilyerrapragadaa we're on https://kth-se.zoom.us/j/69520689359

**Comment by bbaudry** [comment]
13h05, the session is over. I close the issue.
