### ISSUE TITLE
Repetition of planning. 

### ISSUE THREAD

**Issue by MDRezaulHasan** [KTH/devops-course#871]
We want to present our updated PR tomorrow.  But I saw that our name is not adding in repetition planning.

**Comment by gluckzhang** [comment]
Hi @MDRezaulHasan , I don't think you have submitted the PR regarding this. Please do it as soon as possible.

Previous discussion can be found here: https://github.com/KTH/devops-course/issues/862

**Comment by monperrus** [comment]
@MDRezaulHasan I confirm that you must register your repetition via a pull-request on `repetition-planning.md`. Best regards, --Martin Monperrus

**Comment by MDRezaulHasan** [comment]
My partner sends a new pull request. So can you just look at this, is it
ok?

**Comment by gluckzhang** [comment]
@MDRezaulHasan , that PR has been merged. We have already registered the slot for your team.

**Comment by MDRezaulHasan** [comment]
Thanks
