### ISSUE TITLE
Issues regarding Covid19 Project

### ISSUE THREAD

**Issue by sujon2100** [KTH/devops-course#880]
Hi,
We have completed the updated version of the covid19 project. However, We found an issue that we need urgently to discuss. Thanks

**Comment by gluckzhang** [comment]
Hi @sujon2100 , I think you have got contact with us by email. I'll close this issue. Thanks!

**Comment by sujon2100** [comment]
> Hi @sujon2100 , I think you have got contact with us by email. I'll close this issue. Thanks!

Hi @gluckzhang , thanks a lot!
