### ISSUE TITLE
Suggestion to reschedule lesson

### ISSUE THREAD

**Issue by tonikarppi** [KTH/devops-course#90]
The April 25th lesson clashes with the program integrating course lecture for prosamm18, which takes place 15:00-17:00. If the lesson is not rescheduled, I think many people will have to leave in the middle of the lesson.

**Comment by gluckzhang** [comment]
Hi @tonikarppi , thanks for pointing this out. Will discuss with you during next lecture, April 1st :)

**Comment by monperrus** [comment]
Per the discussion this morning all together, too few people are concerned with this problem, so we keep the lecture as planned.

Thanks a lot for raising the problem publicly in a constructive way!
