### ISSUE TITLE
Course automation tasks

### ISSUE THREAD

**Issue by bbaudry** [KTH/devops-course#916]
Collect suggestions for automated tasks that improve the teaching experience and effectiveness.

**Comment by bbaudry** [comment]
Check that all PR submitted for the course come from a Github id that corresponds to one KTH id of a student who registered for the course

**Comment by monperrus** [comment]
Check that there is a valid link to the slides for all presentations.

**Comment by monperrus** [comment]
Check that essays are 2000 words +/- 5%. This can be done with pdftotext.

**Comment by monperrus** [comment]
Send the essays to https://www.urkund.com/ using the Urkund API and give the result as PR status check.

**Comment by monperrus** [comment]
Check that the demo subtitles correspond to the demo voice-over.

**Comment by bbaudry** [comment]
generate a summary readme in for each category folder, based on the content of the contributions

**Comment by AviRoy1988** [comment]
> Send the essays to https://www.urkund.com/ using the Urkund API and give the result as PR status check.

Need help. I want to develop this as git hub action for course automation task. However I could not find the public API lists or any documents for that in the website. Is it possible to get those integration details as student or I need to register as company for that and pay.

**Comment by AviRoy1988** [comment]
> > Send the essays to https://www.urkund.com/ using the Urkund API and give the result as PR status check.
> 
> Need help. I want to develop this as git hub action for course automation task. However I could not find the public API lists or any documents for that in the website. Is it possible to get those integration details as student or I need to register as company for that and pay. @monperrus

**Comment by monperrus** [comment]
great suggestion by @vladomitrovic: it would be great to have some infrastructure to record and share the grading criteria individual items at scale, in a way that that is secure and integrated with KTH identification's system.

**Comment by landeholt** [comment]
Hi, which of these are available to contribute on?
