### ISSUE TITLE
Searching partner for Essay

### ISSUE THREAD

**Issue by yipeitu** [KTH/devops-course#92]
Hi all,
I'm looking for a partner who is interested in automatic deployment for Essay.
The aim is to understand the current modern automatic deployment process and compare with different tools/platforms.
If you're interested in it, please email me (yptu@kth.se)
Thanks.

**Comment by SophieHYe** [comment]
Hi Yipei,
Just wondering would you also interested in doing a demo? Parumita is looking for a partner with a demo in  #85 , maybe you two can have a discussion :) Good luck!

**Comment by yipeitu** [comment]
> Hi Yipei,
> Just wondering would you also interested in doing a demo? Parumita is looking for a partner with a demo in #85 , maybe you two can have a discussion :) Good luck!

Hi Sophie, 
I only need a partner for Essay. Thanks :)
