### ISSUE TITLE
Streaming urls for DevOps 2021

### ISSUE THREAD

**Issue by bbaudry** [KTH/devops-course#924]
Week 1 on zoom
https://www.kth.se/social/course/DD2482/calendar/

**Comment by bbaudry** [comment]
![lecture01](https://user-images.githubusercontent.com/2844085/112113680-684bb480-8bb7-11eb-82cf-7334c51144b9.jpg)

**Comment by SophieHYe** [comment]
Week 2 on zoom 
https://kth-se.zoom.us/j/67189910023
![week2](https://user-images.githubusercontent.com/803666/115353322-e9db3600-a1a7-11eb-87b9-acd5c965aa90.jpeg)

**Comment by cesarsotovalero** [comment]
Week 3 on zoom
https://kth-se.zoom.us/j/64499235220

**Comment by khesoem** [comment]
Week 4 on zoom
[https://kth-se.zoom.us/j/7322533999](https://kth-se.zoom.us/j/7322533999)

![signal-2021-04-20-091054](https://user-images.githubusercontent.com/803666/115353234-cdd79480-a1a7-11eb-9c31-c86757ee5054.jpeg)

**Comment by Deee92** [comment]
Week 5 on Zoom
https://kth-se.zoom.us/j/5279673473

**Comment by SophieHYe** [comment]
Week 6 on Zoom 
https://kth-se.zoom.us/j/66650222454

![signal-2021-05-04-100119](https://user-images.githubusercontent.com/803666/116975401-1fefde00-acaf-11eb-9d8f-b21150f05c75.jpeg)

![IMG_20210504_101925](https://user-images.githubusercontent.com/2844085/116977453-c09bc900-acc2-11eb-89b6-af989ff071b5.jpg)

**Comment by khesoem** [comment]
Week 7 on Zoom
https://kth-se.zoom.us/j/7322533999

![lecture07](https://user-images.githubusercontent.com/2844085/119257704-bd5f7300-bbc6-11eb-8843-e976b83c1c2d.jpg)

**Comment by bbaudry** [comment]
![IMG_20210504_101925](https://user-images.githubusercontent.com/2844085/116977453-c09bc900-acc2-11eb-89b6-af989ff071b5.jpg)

**Comment by bbaudry** [comment]
Week 8 on Zoom
https://kth-se.zoom.us/j/5279673473

![signal-2021-05-18-152013](https://user-images.githubusercontent.com/803666/118658456-eacdaa80-b7db-11eb-9f9d-bf7bd9b4a2ec.jpeg)
