### ISSUE TITLE
Partners wanted - any category

### ISSUE THREAD

**Issue by stephanhorsthemke** [KTH/devops-course#93]
Hey,

I recently switched to this course and do not have partners so far. If you are still searching, feel free to contact me here or vial mail (hors@kth.se).

I already have some ideas, but I am also up for suggestions!

**Comment by gluckzhang** [comment]
Hi @stephanhorsthemke , @Parumita, is it possible for you two to do the demo as a group?
(Relevant issue #85)

**Comment by Parumita** [comment]
Hi @gluckzhang , I have mailed him . But he has managed his group partner already  :(

**Comment by Parumita** [comment]
Hi @gluckzhang , I have mailed him before you said . But he has managed his group partner already :(

**Comment by stephanhorsthemke** [comment]
Yes, I already found partners and i am occupied for the demo now -> closing
